#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 5424026
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : konqueror
Version  : 24.12.0
Release  : 81
URL      : https://download.kde.org/stable/release-service/24.12.0/src/konqueror-24.12.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.12.0/src/konqueror-24.12.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.12.0/src/konqueror-24.12.0.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GFDL-1.2 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: konqueror-bin = %{version}-%{release}
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-lib = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}
Requires: konqueror-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : buildreq-qt6
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kdesu-dev
BuildRequires : kwallet-dev
BuildRequires : plasma-activities-dev
BuildRequires : qt6webengine-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
KWebKitPart
===========
KWebKitPart is a KDE component (KPart) wrapper for QtWebKit. It is intended to
allow KPart based KDE applications such as Konqueror to use it in place of other
browser engine, such as KHTML, to browse the web in Konqueror.

%package bin
Summary: bin components for the konqueror package.
Group: Binaries
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}

%description bin
bin components for the konqueror package.


%package data
Summary: data components for the konqueror package.
Group: Data

%description data
data components for the konqueror package.


%package dev
Summary: dev components for the konqueror package.
Group: Development
Requires: konqueror-lib = %{version}-%{release}
Requires: konqueror-bin = %{version}-%{release}
Requires: konqueror-data = %{version}-%{release}
Provides: konqueror-devel = %{version}-%{release}
Requires: konqueror = %{version}-%{release}

%description dev
dev components for the konqueror package.


%package doc
Summary: doc components for the konqueror package.
Group: Documentation

%description doc
doc components for the konqueror package.


%package lib
Summary: lib components for the konqueror package.
Group: Libraries
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}

%description lib
lib components for the konqueror package.


%package license
Summary: license components for the konqueror package.
Group: Default

%description license
license components for the konqueror package.


%package locales
Summary: locales components for the konqueror package.
Group: Default

%description locales
locales components for the konqueror package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n konqueror-24.12.0
cd %{_builddir}/konqueror-24.12.0
pushd ..
cp -a konqueror-24.12.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735195900
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735195900
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/konqueror
cp %{_builddir}/konqueror-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/konqueror/ea97eb88ae53ec41e26f8542176ab986d7bc943a || :
cp %{_builddir}/konqueror-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/konqueror/f1946dab78e58c04c8c25ec6b074f5fc5c2830fe || :
cp %{_builddir}/konqueror-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/konqueror/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/konqueror/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/konqueror/2123756e0b1fc8243547235a33c0fcabfe3b9a51 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/konqueror/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/konqueror/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/konqueror/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/konqueror/19d98e1b6f8ef12849ea4012a052d3907f336c91 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/konqueror/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/konqueror/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/konqueror/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/konqueror/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/konqueror-%{version}/plugins/COPYING.DOC %{buildroot}/usr/share/package-licenses/konqueror/bd75d59f9d7d9731bfabdc48ecd19e704d218e38 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang babelfish
%find_lang dirfilterplugin
%find_lang imgalleryplugin
%find_lang kcmbookmarks
%find_lang kcmkonq
%find_lang kcmkonqhtml
%find_lang kcmperformance
%find_lang kfmclient
%find_lang kgetplugin
%find_lang khtmlsettingsplugin
%find_lang khtmltts
%find_lang konqueror
%find_lang kshellcmdplugin
%find_lang libkonq
%find_lang uachangerplugin
%find_lang akregator_konqplugin
%find_lang autorefresh
%find_lang fsview
%find_lang kio6_bookmarks
%find_lang searchbarplugin
%find_lang webarchiver
%find_lang webenginepart
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/fsview
/V3/usr/bin/kcreatewebarchive
/V3/usr/bin/kfmclient
/V3/usr/bin/konqueror
/usr/bin/fsview
/usr/bin/kcreatewebarchive
/usr/bin/kfmclient
/usr/bin/konqueror

%files data
%defattr(-,root,root,-)
/usr/share/akregator/pics/feed.png
/usr/share/applications/bookmarks.desktop
/usr/share/applications/kcm_bookmarks.desktop
/usr/share/applications/kfmclient.desktop
/usr/share/applications/kfmclient_dir.desktop
/usr/share/applications/kfmclient_html.desktop
/usr/share/applications/kfmclient_war.desktop
/usr/share/applications/konqbrowser.desktop
/usr/share/applications/org.kde.konqueror.desktop
/usr/share/config.kcfg/kcreatewebarchive.kcfg
/usr/share/config.kcfg/konqueror.kcfg
/usr/share/dbus-1/interfaces/org.kde.Konqueror.Main.xml
/usr/share/dbus-1/interfaces/org.kde.Konqueror.MainWindow.xml
/usr/share/icons/hicolor/128x128/apps/konqueror.png
/usr/share/icons/hicolor/128x128/apps/webengine.png
/usr/share/icons/hicolor/16x16/actions/babelfish.png
/usr/share/icons/hicolor/16x16/actions/imagegallery.png
/usr/share/icons/hicolor/16x16/actions/webarchiver.png
/usr/share/icons/hicolor/16x16/apps/konqueror.png
/usr/share/icons/hicolor/16x16/apps/webengine.png
/usr/share/icons/hicolor/22x22/actions/babelfish.png
/usr/share/icons/hicolor/22x22/actions/imagegallery.png
/usr/share/icons/hicolor/22x22/actions/webarchiver.png
/usr/share/icons/hicolor/22x22/apps/fsview.png
/usr/share/icons/hicolor/22x22/apps/konqueror.png
/usr/share/icons/hicolor/22x22/apps/webengine.png
/usr/share/icons/hicolor/32x32/apps/fsview.png
/usr/share/icons/hicolor/32x32/apps/konqueror.png
/usr/share/icons/hicolor/32x32/apps/webengine.png
/usr/share/icons/hicolor/48x48/apps/konqueror.png
/usr/share/icons/hicolor/48x48/apps/webengine.png
/usr/share/icons/hicolor/64x64/apps/konqueror.png
/usr/share/icons/hicolor/64x64/apps/webengine.png
/usr/share/kcmcss/template.css
/usr/share/kconf_update/webenginepart.upd
/usr/share/kcontrol/pics/onlyone.png
/usr/share/kcontrol/pics/overlapping.png
/usr/share/kf6/kbookmark/directory_bookmarkbar.desktop
/usr/share/kio_bookmarks/kio_bookmarks.css
/usr/share/konqsidebartng/entries/bookmarks.desktop
/usr/share/konqsidebartng/entries/fonts.desktop
/usr/share/konqsidebartng/entries/history.desktop
/usr/share/konqsidebartng/entries/home.desktop
/usr/share/konqsidebartng/entries/places.desktop
/usr/share/konqsidebartng/entries/remote.desktop
/usr/share/konqsidebartng/entries/root.desktop
/usr/share/konqsidebartng/entries/services.desktop
/usr/share/konqueror/about/body-background.png
/usr/share/konqueror/about/box-bottom-left.png
/usr/share/konqueror/about/box-bottom-middle.png
/usr/share/konqueror/about/box-bottom-right.png
/usr/share/konqueror/about/box-center.png
/usr/share/konqueror/about/box-middle-left.png
/usr/share/konqueror/about/box-middle-right.png
/usr/share/konqueror/about/box-top-left.png
/usr/share/konqueror/about/box-top-middle.png
/usr/share/konqueror/about/box-top-right.png
/usr/share/konqueror/about/intro.html
/usr/share/konqueror/about/kde_infopage.css
/usr/share/konqueror/about/kde_infopage_rtl.css
/usr/share/konqueror/about/konq.css
/usr/share/konqueror/about/launch.html
/usr/share/konqueror/about/plugins.html
/usr/share/konqueror/about/plugins_rtl.html
/usr/share/konqueror/about/tips.html
/usr/share/konqueror/about/top-left-konqueror.png
/usr/share/konqueror/about/top-middle.png
/usr/share/konqueror/icons/hicolor/16x16/actions/google.png
/usr/share/konqueror/icons/hicolor/22x22/actions/google.png
/usr/share/konqueror/icons/hicolor/32x32/actions/google.png
/usr/share/konqueror/icons/hicolor/48x48/actions/google.png
/usr/share/konqueror/icons/hicolor/64x64/actions/google.png
/usr/share/konqueror/icons/hicolor/scalable/actions/google.svgz
/usr/share/konqueror/partsrcfiles/akregatorkonqfeedicon.rc
/usr/share/konqueror/partsrcfiles/autorefresh.rc
/usr/share/konqueror/partsrcfiles/babelfishplugin.rc
/usr/share/konqueror/partsrcfiles/dirfilterplugin.rc
/usr/share/konqueror/partsrcfiles/khtmlsettingsplugin.rc
/usr/share/konqueror/partsrcfiles/kimgallery.rc
/usr/share/konqueror/partsrcfiles/konq_shellcmdplugin.rc
/usr/share/konqueror/partsrcfiles/konqueror_kget_browser_integration.rc
/usr/share/konqueror/partsrcfiles/searchbarplugin.rc
/usr/share/konqueror/partsrcfiles/uachangerplugin.rc
/usr/share/konqueror/partsrcfiles/webarchiverplugin.rc
/usr/share/konqueror/pics/indicator_connect.png
/usr/share/konqueror/pics/indicator_empty.png
/usr/share/konqueror/pics/indicator_noconnect.png
/usr/share/konqueror/pics/indicator_viewactive.png
/usr/share/metainfo/org.kde.konqueror.appdata.xml
/usr/share/qlogging-categories6/akregatorplugin.categories
/usr/share/qlogging-categories6/fsview.categories
/usr/share/qlogging-categories6/konqueror.categories
/usr/share/webenginepart/error.html
/usr/share/xdg/autostart/konqy_preload.desktop
/usr/share/xdg/konqsidebartngrc
/usr/share/xdg/translaterc
/usr/share/xdg/useragenttemplatesrc

%files dev
%defattr(-,root,root,-)
/V3/usr/lib64/libkwebenginepart.so
/usr/include/KF6/konq_events.h
/usr/include/KF6/konq_historyentry.h
/usr/include/KF6/konq_historyprovider.h
/usr/include/KF6/konq_kpart_plugin.h
/usr/include/KF6/konq_popupmenu.h
/usr/include/KF6/konq_version.h
/usr/include/KF6/konqsettings.h
/usr/include/KF6/konqsettings_version.h
/usr/include/KF6/konqsidebarplugin.h
/usr/include/KF6/libkonq_export.h
/usr/include/KF6/libkonqsettings_export.h
/usr/include/KF6/selectorinterface.h
/usr/lib64/cmake/KF6Konq/KF6KonqConfig.cmake
/usr/lib64/cmake/KF6Konq/KF6KonqConfigVersion.cmake
/usr/lib64/cmake/KF6Konq/KF6KonqSettingsConfig.cmake
/usr/lib64/cmake/KF6Konq/KF6KonqSettingsConfigVersion.cmake
/usr/lib64/cmake/KF6Konq/KF6KonqSettingsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6Konq/KF6KonqSettingsTargets.cmake
/usr/lib64/cmake/KF6Konq/KF6KonqTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6Konq/KF6KonqTargets.cmake
/usr/lib64/libKF6Konq.so
/usr/lib64/libKF6KonqSettings.so
/usr/lib64/libkonqsidebarplugin.so
/usr/lib64/libkwebenginepart.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/ca/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/ca/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/history/index.docbook
/usr/share/doc/HTML/ca/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/ca/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/ca/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/ca/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/ca/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/ca/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol/performance/index.docbook
/usr/share/doc/HTML/ca/konqueror/index.cache.bz2
/usr/share/doc/HTML/ca/konqueror/index.docbook
/usr/share/doc/HTML/ca/konqueror/konqorg.png
/usr/share/doc/HTML/ca/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/de/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/de/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/de/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/history/index.docbook
/usr/share/doc/HTML/de/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/de/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/de/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/de/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/de/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/de/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol/performance/index.docbook
/usr/share/doc/HTML/el/konqueror/basics.docbook
/usr/share/doc/HTML/el/konqueror/bookmarks.docbook
/usr/share/doc/HTML/el/konqueror/browser.docbook
/usr/share/doc/HTML/el/konqueror/cmndline.png
/usr/share/doc/HTML/el/konqueror/commands.docbook
/usr/share/doc/HTML/el/konqueror/config.docbook
/usr/share/doc/HTML/el/konqueror/credits.docbook
/usr/share/doc/HTML/el/konqueror/dirtree.png
/usr/share/doc/HTML/el/konqueror/dragdrop.png
/usr/share/doc/HTML/el/konqueror/faq.docbook
/usr/share/doc/HTML/el/konqueror/filemanager.docbook
/usr/share/doc/HTML/el/konqueror/folders.png
/usr/share/doc/HTML/el/konqueror/index.cache.bz2
/usr/share/doc/HTML/el/konqueror/index.docbook
/usr/share/doc/HTML/el/konqueror/introduction.docbook
/usr/share/doc/HTML/el/konqueror/konqorg.png
/usr/share/doc/HTML/el/konqueror/look.png
/usr/share/doc/HTML/el/konqueror/parts.png
/usr/share/doc/HTML/el/konqueror/path-complete.docbook
/usr/share/doc/HTML/el/konqueror/plugins.docbook
/usr/share/doc/HTML/el/konqueror/save-settings.docbook
/usr/share/doc/HTML/el/konqueror/shortcut1.png
/usr/share/doc/HTML/el/konqueror/shortcut2.png
/usr/share/doc/HTML/el/konqueror/sidebar.docbook
/usr/share/doc/HTML/el/konqueror/thumbnails.png
/usr/share/doc/HTML/el/konqueror/view-extensions.docbook
/usr/share/doc/HTML/el/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/en/kcontrol6/bookmarks/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/bookmarks/index.docbook
/usr/share/doc/HTML/en/kcontrol6/filemanager/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/filemanager/index.docbook
/usr/share/doc/HTML/en/kcontrol6/kcmcss/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/kcmcss/index.docbook
/usr/share/doc/HTML/en/kcontrol6/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/khtml-adblock/index.docbook
/usr/share/doc/HTML/en/kcontrol6/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/khtml-behavior/index.docbook
/usr/share/doc/HTML/en/kcontrol6/khtml-general/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/khtml-general/index.docbook
/usr/share/doc/HTML/en/kcontrol6/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/khtml-java-js/index.docbook
/usr/share/doc/HTML/en/kcontrol6/performance/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol6/performance/index.docbook
/usr/share/doc/HTML/en/konqueror/cmndline.png
/usr/share/doc/HTML/en/konqueror/dirtree.png
/usr/share/doc/HTML/en/konqueror/dragdrop.png
/usr/share/doc/HTML/en/konqueror/folders.png
/usr/share/doc/HTML/en/konqueror/format-font-size-less.png
/usr/share/doc/HTML/en/konqueror/format-font-size-more.png
/usr/share/doc/HTML/en/konqueror/go-jump.png
/usr/share/doc/HTML/en/konqueror/grouping-view.png
/usr/share/doc/HTML/en/konqueror/index.cache.bz2
/usr/share/doc/HTML/en/konqueror/index.docbook
/usr/share/doc/HTML/en/konqueror/konqorg.png
/usr/share/doc/HTML/en/konqueror/look.png
/usr/share/doc/HTML/en/konqueror/parts.png
/usr/share/doc/HTML/en/konqueror/reset.png
/usr/share/doc/HTML/en/konqueror/thumbnails.png
/usr/share/doc/HTML/en/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/es/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/es/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/es/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/history/index.docbook
/usr/share/doc/HTML/es/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/es/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/es/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/es/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/es/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/es/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol/performance/index.docbook
/usr/share/doc/HTML/es/konqueror/basics.docbook
/usr/share/doc/HTML/es/konqueror/bookmarks.docbook
/usr/share/doc/HTML/es/konqueror/browser.docbook
/usr/share/doc/HTML/es/konqueror/commands.docbook
/usr/share/doc/HTML/es/konqueror/config.docbook
/usr/share/doc/HTML/es/konqueror/credits.docbook
/usr/share/doc/HTML/es/konqueror/faq.docbook
/usr/share/doc/HTML/es/konqueror/filemanager.docbook
/usr/share/doc/HTML/es/konqueror/index.cache.bz2
/usr/share/doc/HTML/es/konqueror/index.docbook
/usr/share/doc/HTML/es/konqueror/introduction.docbook
/usr/share/doc/HTML/es/konqueror/path-complete.docbook
/usr/share/doc/HTML/es/konqueror/plugins.docbook
/usr/share/doc/HTML/es/konqueror/save-settings.docbook
/usr/share/doc/HTML/es/konqueror/sidebar.docbook
/usr/share/doc/HTML/es/konqueror/view-extensions.docbook
/usr/share/doc/HTML/et/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/et/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/et/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/history/index.docbook
/usr/share/doc/HTML/et/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/et/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/et/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/et/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/et/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/et/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol/performance/index.docbook
/usr/share/doc/HTML/fr/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/fr/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/fr/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/history/index.docbook
/usr/share/doc/HTML/fr/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/fr/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/fr/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/fr/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/fr/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/fr/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol/performance/index.docbook
/usr/share/doc/HTML/fr/konqueror/basics.docbook
/usr/share/doc/HTML/fr/konqueror/bookmarks.docbook
/usr/share/doc/HTML/fr/konqueror/browser.docbook
/usr/share/doc/HTML/fr/konqueror/cmndline.png
/usr/share/doc/HTML/fr/konqueror/commands.docbook
/usr/share/doc/HTML/fr/konqueror/config.docbook
/usr/share/doc/HTML/fr/konqueror/credits.docbook
/usr/share/doc/HTML/fr/konqueror/dirtree.png
/usr/share/doc/HTML/fr/konqueror/dragdrop.png
/usr/share/doc/HTML/fr/konqueror/faq.docbook
/usr/share/doc/HTML/fr/konqueror/filemanager.docbook
/usr/share/doc/HTML/fr/konqueror/index.cache.bz2
/usr/share/doc/HTML/fr/konqueror/index.docbook
/usr/share/doc/HTML/fr/konqueror/introduction.docbook
/usr/share/doc/HTML/fr/konqueror/konqorg.png
/usr/share/doc/HTML/fr/konqueror/parts.png
/usr/share/doc/HTML/fr/konqueror/path-complete.docbook
/usr/share/doc/HTML/fr/konqueror/plugins.docbook
/usr/share/doc/HTML/fr/konqueror/save-settings.docbook
/usr/share/doc/HTML/fr/konqueror/shortcut1.png
/usr/share/doc/HTML/fr/konqueror/shortcut2.png
/usr/share/doc/HTML/fr/konqueror/sidebar.docbook
/usr/share/doc/HTML/fr/konqueror/view-extensions.docbook
/usr/share/doc/HTML/it/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/it/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/it/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/history/index.docbook
/usr/share/doc/HTML/it/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/it/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/it/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/it/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/it/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/it/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol/performance/index.docbook
/usr/share/doc/HTML/it/konqueror/index.cache.bz2
/usr/share/doc/HTML/it/konqueror/index.docbook
/usr/share/doc/HTML/ko/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/ko/kcontrol/performance/index.docbook
/usr/share/doc/HTML/nb/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/nb/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol/history/index.docbook
/usr/share/doc/HTML/nb/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/nl/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/nl/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/nl/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/history/index.docbook
/usr/share/doc/HTML/nl/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/nl/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/nl/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/nl/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/nl/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/nl/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol/performance/index.docbook
/usr/share/doc/HTML/nl/konqueror/basics.docbook
/usr/share/doc/HTML/nl/konqueror/bookmarks.docbook
/usr/share/doc/HTML/nl/konqueror/browser.docbook
/usr/share/doc/HTML/nl/konqueror/cmndline.png
/usr/share/doc/HTML/nl/konqueror/commands.docbook
/usr/share/doc/HTML/nl/konqueror/config.docbook
/usr/share/doc/HTML/nl/konqueror/credits.docbook
/usr/share/doc/HTML/nl/konqueror/dirtree.png
/usr/share/doc/HTML/nl/konqueror/dragdrop.png
/usr/share/doc/HTML/nl/konqueror/faq.docbook
/usr/share/doc/HTML/nl/konqueror/filemanager.docbook
/usr/share/doc/HTML/nl/konqueror/index.cache.bz2
/usr/share/doc/HTML/nl/konqueror/index.docbook
/usr/share/doc/HTML/nl/konqueror/introduction.docbook
/usr/share/doc/HTML/nl/konqueror/konqorg.png
/usr/share/doc/HTML/nl/konqueror/parts.png
/usr/share/doc/HTML/nl/konqueror/path-complete.docbook
/usr/share/doc/HTML/nl/konqueror/plugins.docbook
/usr/share/doc/HTML/nl/konqueror/save-settings.docbook
/usr/share/doc/HTML/nl/konqueror/shortcut1.png
/usr/share/doc/HTML/nl/konqueror/shortcut2.png
/usr/share/doc/HTML/nl/konqueror/sidebar.docbook
/usr/share/doc/HTML/nl/konqueror/view-extensions.docbook
/usr/share/doc/HTML/pt/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/pt/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/pt/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/history/index.docbook
/usr/share/doc/HTML/pt/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/pt/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/pt/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/pt/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/pt/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/pt/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol/performance/index.docbook
/usr/share/doc/HTML/pt/konqueror/basics.docbook
/usr/share/doc/HTML/pt/konqueror/bookmarks.docbook
/usr/share/doc/HTML/pt/konqueror/browser.docbook
/usr/share/doc/HTML/pt/konqueror/commands.docbook
/usr/share/doc/HTML/pt/konqueror/config.docbook
/usr/share/doc/HTML/pt/konqueror/credits.docbook
/usr/share/doc/HTML/pt/konqueror/faq.docbook
/usr/share/doc/HTML/pt/konqueror/filemanager.docbook
/usr/share/doc/HTML/pt/konqueror/index.cache.bz2
/usr/share/doc/HTML/pt/konqueror/index.docbook
/usr/share/doc/HTML/pt/konqueror/introduction.docbook
/usr/share/doc/HTML/pt/konqueror/path-complete.docbook
/usr/share/doc/HTML/pt/konqueror/plugins.docbook
/usr/share/doc/HTML/pt/konqueror/save-settings.docbook
/usr/share/doc/HTML/pt/konqueror/sidebar.docbook
/usr/share/doc/HTML/pt/konqueror/view-extensions.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/history/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol/performance/index.docbook
/usr/share/doc/HTML/pt_BR/konqueror/cmndline.png
/usr/share/doc/HTML/pt_BR/konqueror/dirtree.png
/usr/share/doc/HTML/pt_BR/konqueror/dragdrop.png
/usr/share/doc/HTML/pt_BR/konqueror/folders.png
/usr/share/doc/HTML/pt_BR/konqueror/index.cache.bz2
/usr/share/doc/HTML/pt_BR/konqueror/index.docbook
/usr/share/doc/HTML/pt_BR/konqueror/konqorg.png
/usr/share/doc/HTML/pt_BR/konqueror/look.png
/usr/share/doc/HTML/pt_BR/konqueror/parts.png
/usr/share/doc/HTML/pt_BR/konqueror/shortcut1.png
/usr/share/doc/HTML/pt_BR/konqueror/shortcut2.png
/usr/share/doc/HTML/pt_BR/konqueror/thumbnails.png
/usr/share/doc/HTML/pt_BR/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/ru/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/ru/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/ru/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/history/index.docbook
/usr/share/doc/HTML/ru/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/ru/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/ru/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/ru/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/ru/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/ru/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/ru/kcontrol/performance/index.docbook
/usr/share/doc/HTML/sl/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/sl/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/sl/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/history/index.docbook
/usr/share/doc/HTML/sl/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/sl/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/sl/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/sl/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/sl/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/sl/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/sl/kcontrol/performance/index.docbook
/usr/share/doc/HTML/sl/konqueror/index.cache.bz2
/usr/share/doc/HTML/sl/konqueror/index.docbook
/usr/share/doc/HTML/sr/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/sr/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/sr/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/sr/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/sr/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/sr/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/sr/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/sr/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol/performance/index.docbook
/usr/share/doc/HTML/sr/konqueror/basics.docbook
/usr/share/doc/HTML/sr/konqueror/bookmarks.docbook
/usr/share/doc/HTML/sr/konqueror/browser.docbook
/usr/share/doc/HTML/sr/konqueror/commands.docbook
/usr/share/doc/HTML/sr/konqueror/config.docbook
/usr/share/doc/HTML/sr/konqueror/credits.docbook
/usr/share/doc/HTML/sr/konqueror/faq.docbook
/usr/share/doc/HTML/sr/konqueror/filemanager.docbook
/usr/share/doc/HTML/sr/konqueror/index.cache.bz2
/usr/share/doc/HTML/sr/konqueror/index.docbook
/usr/share/doc/HTML/sr/konqueror/introduction.docbook
/usr/share/doc/HTML/sr/konqueror/path-complete.docbook
/usr/share/doc/HTML/sr/konqueror/plugins.docbook
/usr/share/doc/HTML/sr/konqueror/save-settings.docbook
/usr/share/doc/HTML/sr/konqueror/sidebar.docbook
/usr/share/doc/HTML/sr/konqueror/view-extensions.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/sr@latin/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kcontrol/performance/index.docbook
/usr/share/doc/HTML/sr@latin/konqueror/basics.docbook
/usr/share/doc/HTML/sr@latin/konqueror/bookmarks.docbook
/usr/share/doc/HTML/sr@latin/konqueror/browser.docbook
/usr/share/doc/HTML/sr@latin/konqueror/commands.docbook
/usr/share/doc/HTML/sr@latin/konqueror/config.docbook
/usr/share/doc/HTML/sr@latin/konqueror/credits.docbook
/usr/share/doc/HTML/sr@latin/konqueror/faq.docbook
/usr/share/doc/HTML/sr@latin/konqueror/filemanager.docbook
/usr/share/doc/HTML/sr@latin/konqueror/index.cache.bz2
/usr/share/doc/HTML/sr@latin/konqueror/index.docbook
/usr/share/doc/HTML/sr@latin/konqueror/introduction.docbook
/usr/share/doc/HTML/sr@latin/konqueror/path-complete.docbook
/usr/share/doc/HTML/sr@latin/konqueror/plugins.docbook
/usr/share/doc/HTML/sr@latin/konqueror/save-settings.docbook
/usr/share/doc/HTML/sr@latin/konqueror/sidebar.docbook
/usr/share/doc/HTML/sr@latin/konqueror/view-extensions.docbook
/usr/share/doc/HTML/sv/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/sv/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/sv/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/history/index.docbook
/usr/share/doc/HTML/sv/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/sv/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/sv/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/sv/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/sv/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/sv/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol/performance/index.docbook
/usr/share/doc/HTML/sv/konqueror/cmndline.png
/usr/share/doc/HTML/sv/konqueror/dirtree.png
/usr/share/doc/HTML/sv/konqueror/dragdrop.png
/usr/share/doc/HTML/sv/konqueror/index.cache.bz2
/usr/share/doc/HTML/sv/konqueror/index.docbook
/usr/share/doc/HTML/sv/konqueror/konqorg.png
/usr/share/doc/HTML/sv/konqueror/parts.png
/usr/share/doc/HTML/sv/konqueror/shortcut1.png
/usr/share/doc/HTML/sv/konqueror/shortcut2.png
/usr/share/doc/HTML/tr/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/tr/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/tr/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/history/index.docbook
/usr/share/doc/HTML/tr/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/tr/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/tr/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/tr/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/tr/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/tr/kcontrol/performance/index.docbook
/usr/share/doc/HTML/uk/kcontrol/bookmarks/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/bookmarks/index.docbook
/usr/share/doc/HTML/uk/kcontrol/filemanager/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/filemanager/index.docbook
/usr/share/doc/HTML/uk/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/history/index.docbook
/usr/share/doc/HTML/uk/kcontrol/kcmcss/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/kcmcss/index.docbook
/usr/share/doc/HTML/uk/kcontrol/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/khtml-adblock/index.docbook
/usr/share/doc/HTML/uk/kcontrol/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/khtml-behavior/index.docbook
/usr/share/doc/HTML/uk/kcontrol/khtml-general/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/khtml-general/index.docbook
/usr/share/doc/HTML/uk/kcontrol/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/khtml-java-js/index.docbook
/usr/share/doc/HTML/uk/kcontrol/performance/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol/performance/index.docbook
/usr/share/doc/HTML/uk/konqueror/cmndline.png
/usr/share/doc/HTML/uk/konqueror/dirtree.png
/usr/share/doc/HTML/uk/konqueror/dragdrop.png
/usr/share/doc/HTML/uk/konqueror/folders.png
/usr/share/doc/HTML/uk/konqueror/index.cache.bz2
/usr/share/doc/HTML/uk/konqueror/index.docbook
/usr/share/doc/HTML/uk/konqueror/konqorg.png
/usr/share/doc/HTML/uk/konqueror/look.png
/usr/share/doc/HTML/uk/konqueror/parts.png
/usr/share/doc/HTML/uk/konqueror/thumbnails.png
/usr/share/doc/HTML/uk/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/zh_CN/kcontrol/history/index.cache.bz2
/usr/share/doc/HTML/zh_CN/kcontrol/history/index.docbook

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKF6Konq.so.5.97.0
/V3/usr/lib64/libKF6KonqSettings.so.5.97.0
/V3/usr/lib64/libkonqsidebarplugin.so.24.12.0
/V3/usr/lib64/libkonquerorprivate.so.24.12.0
/V3/usr/lib64/qt6/plugins/akregatorkonqfeedicon.so
/V3/usr/lib64/qt6/plugins/autorefresh.so
/V3/usr/lib64/qt6/plugins/babelfishplugin.so
/V3/usr/lib64/qt6/plugins/dolphinpart/kpartplugins/dirfilterplugin.so
/V3/usr/lib64/qt6/plugins/dolphinpart/kpartplugins/kimgallery.so
/V3/usr/lib64/qt6/plugins/dolphinpart/kpartplugins/konq_shellcmdplugin.so
/V3/usr/lib64/qt6/plugins/kf6/kfileitemaction/akregatorplugin.so
/V3/usr/lib64/qt6/plugins/kf6/kio/bookmarks.so
/V3/usr/lib64/qt6/plugins/kf6/parts/fsviewpart.so
/V3/usr/lib64/qt6/plugins/kf6/parts/konq_sidebar.so
/V3/usr/lib64/qt6/plugins/kf6/parts/webenginepart.so
/V3/usr/lib64/qt6/plugins/kf6/thumbcreator/webarchivethumbnail.so
/V3/usr/lib64/qt6/plugins/khtmlsettingsplugin.so
/V3/usr/lib64/qt6/plugins/konqueror/kpartplugins/searchbarplugin.so
/V3/usr/lib64/qt6/plugins/konqueror/sidebar/konqsidebar_bookmarks.so
/V3/usr/lib64/qt6/plugins/konqueror/sidebar/konqsidebar_history.so
/V3/usr/lib64/qt6/plugins/konqueror/sidebar/konqsidebar_places.so
/V3/usr/lib64/qt6/plugins/konqueror/sidebar/konqsidebar_tree.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/kcm_bookmarks.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/kcm_history.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/kcm_konq.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/kcm_performance.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_appearance.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_behavior.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_cache.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_cookies.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_filter.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_general.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_java_js.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_tabs.so
/V3/usr/lib64/qt6/plugins/konqueror_kcms/khtml_useragent.so
/V3/usr/lib64/qt6/plugins/konqueror_kget_browser_integration.so
/V3/usr/lib64/qt6/plugins/uachangerplugin.so
/V3/usr/lib64/qt6/plugins/webarchiverplugin.so
/usr/lib64/libKF6Konq.so.5.97.0
/usr/lib64/libKF6Konq.so.7
/usr/lib64/libKF6KonqSettings.so.5.97.0
/usr/lib64/libKF6KonqSettings.so.7
/usr/lib64/libkonqsidebarplugin.so.24.12.0
/usr/lib64/libkonqsidebarplugin.so.6
/usr/lib64/libkonquerorprivate.so.24.12.0
/usr/lib64/libkonquerorprivate.so.5
/usr/lib64/qt6/plugins/akregatorkonqfeedicon.so
/usr/lib64/qt6/plugins/autorefresh.so
/usr/lib64/qt6/plugins/babelfishplugin.so
/usr/lib64/qt6/plugins/dolphinpart/kpartplugins/dirfilterplugin.so
/usr/lib64/qt6/plugins/dolphinpart/kpartplugins/kimgallery.so
/usr/lib64/qt6/plugins/dolphinpart/kpartplugins/konq_shellcmdplugin.so
/usr/lib64/qt6/plugins/kf6/kfileitemaction/akregatorplugin.so
/usr/lib64/qt6/plugins/kf6/kio/bookmarks.so
/usr/lib64/qt6/plugins/kf6/parts/fsviewpart.so
/usr/lib64/qt6/plugins/kf6/parts/konq_sidebar.so
/usr/lib64/qt6/plugins/kf6/parts/webenginepart.so
/usr/lib64/qt6/plugins/kf6/thumbcreator/webarchivethumbnail.so
/usr/lib64/qt6/plugins/khtml/kpartplugins/akregatorkonqfeediconkhtml_kpartplugins.so
/usr/lib64/qt6/plugins/khtml/kpartplugins/autorefreshkhtml_kpartplugins.so
/usr/lib64/qt6/plugins/khtml/kpartplugins/babelfishpluginkhtml_kpartplugins.so
/usr/lib64/qt6/plugins/khtml/kpartplugins/khtmlsettingspluginkhtml_kpartplugins.so
/usr/lib64/qt6/plugins/khtml/kpartplugins/konqueror_kget_browser_integrationkhtml_kpartplugins.so
/usr/lib64/qt6/plugins/khtml/kpartplugins/uachangerpluginkhtml_kpartplugins.so
/usr/lib64/qt6/plugins/khtml/kpartplugins/webarchiverpluginkhtml_kpartplugins.so
/usr/lib64/qt6/plugins/khtmlsettingsplugin.so
/usr/lib64/qt6/plugins/konqueror/kpartplugins/searchbarplugin.so
/usr/lib64/qt6/plugins/konqueror/sidebar/konqsidebar_bookmarks.so
/usr/lib64/qt6/plugins/konqueror/sidebar/konqsidebar_history.so
/usr/lib64/qt6/plugins/konqueror/sidebar/konqsidebar_places.so
/usr/lib64/qt6/plugins/konqueror/sidebar/konqsidebar_tree.so
/usr/lib64/qt6/plugins/konqueror_kcms/kcm_bookmarks.so
/usr/lib64/qt6/plugins/konqueror_kcms/kcm_history.so
/usr/lib64/qt6/plugins/konqueror_kcms/kcm_konq.so
/usr/lib64/qt6/plugins/konqueror_kcms/kcm_performance.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_appearance.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_behavior.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_cache.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_cookies.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_filter.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_general.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_java_js.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_tabs.so
/usr/lib64/qt6/plugins/konqueror_kcms/khtml_useragent.so
/usr/lib64/qt6/plugins/konqueror_kget_browser_integration.so
/usr/lib64/qt6/plugins/kwebkitpart/kpartplugins/akregatorkonqfeediconkwebkitpart_kpartplugins.so
/usr/lib64/qt6/plugins/kwebkitpart/kpartplugins/autorefreshkwebkitpart_kpartplugins.so
/usr/lib64/qt6/plugins/kwebkitpart/kpartplugins/babelfishpluginkwebkitpart_kpartplugins.so
/usr/lib64/qt6/plugins/kwebkitpart/kpartplugins/khtmlsettingspluginkwebkitpart_kpartplugins.so
/usr/lib64/qt6/plugins/kwebkitpart/kpartplugins/konqueror_kget_browser_integrationkwebkitpart_kpartplugins.so
/usr/lib64/qt6/plugins/kwebkitpart/kpartplugins/uachangerpluginkwebkitpart_kpartplugins.so
/usr/lib64/qt6/plugins/kwebkitpart/kpartplugins/webarchiverpluginkwebkitpart_kpartplugins.so
/usr/lib64/qt6/plugins/uachangerplugin.so
/usr/lib64/qt6/plugins/webarchiverplugin.so
/usr/lib64/qt6/plugins/webenginepart/kpartplugins/akregatorkonqfeediconwebenginepart_kpartplugins.so
/usr/lib64/qt6/plugins/webenginepart/kpartplugins/autorefreshwebenginepart_kpartplugins.so
/usr/lib64/qt6/plugins/webenginepart/kpartplugins/babelfishpluginwebenginepart_kpartplugins.so
/usr/lib64/qt6/plugins/webenginepart/kpartplugins/khtmlsettingspluginwebenginepart_kpartplugins.so
/usr/lib64/qt6/plugins/webenginepart/kpartplugins/konqueror_kget_browser_integrationwebenginepart_kpartplugins.so
/usr/lib64/qt6/plugins/webenginepart/kpartplugins/uachangerpluginwebenginepart_kpartplugins.so
/usr/lib64/qt6/plugins/webenginepart/kpartplugins/webarchiverpluginwebenginepart_kpartplugins.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/konqueror/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/konqueror/2123756e0b1fc8243547235a33c0fcabfe3b9a51
/usr/share/package-licenses/konqueror/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/konqueror/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/konqueror/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/konqueror/a4c60b3fefda228cd7439d3565df043192fef137
/usr/share/package-licenses/konqueror/bd75d59f9d7d9731bfabdc48ecd19e704d218e38
/usr/share/package-licenses/konqueror/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/konqueror/ea97eb88ae53ec41e26f8542176ab986d7bc943a
/usr/share/package-licenses/konqueror/f1946dab78e58c04c8c25ec6b074f5fc5c2830fe

%files locales -f babelfish.lang -f dirfilterplugin.lang -f imgalleryplugin.lang -f kcmbookmarks.lang -f kcmkonq.lang -f kcmkonqhtml.lang -f kcmperformance.lang -f kfmclient.lang -f kgetplugin.lang -f khtmlsettingsplugin.lang -f khtmltts.lang -f konqueror.lang -f kshellcmdplugin.lang -f libkonq.lang -f uachangerplugin.lang -f akregator_konqplugin.lang -f autorefresh.lang -f fsview.lang -f kio6_bookmarks.lang -f searchbarplugin.lang -f webarchiver.lang -f webenginepart.lang
%defattr(-,root,root,-)

