#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : konqueror
Version  : 20.08.0
Release  : 24
URL      : https://download.kde.org/stable/release-service/20.08.0/src/konqueror-20.08.0.tar.xz
Source0  : https://download.kde.org/stable/release-service/20.08.0/src/konqueror-20.08.0.tar.xz
Source1  : https://download.kde.org/stable/release-service/20.08.0/src/konqueror-20.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GFDL-1.3 GPL-2.0 LGPL-2.1
Requires: konqueror-bin = %{version}-%{release}
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-lib = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}
Requires: konqueror-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : kactivities-dev
BuildRequires : kdesu-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtspeech-dev
BuildRequires : qtwebengine-dev
BuildRequires : zlib-dev

%description
Konqueror Plugins
=====================================================================
This module contains plugins that interact with Konqueror.

%package bin
Summary: bin components for the konqueror package.
Group: Binaries
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}

%description bin
bin components for the konqueror package.


%package data
Summary: data components for the konqueror package.
Group: Data

%description data
data components for the konqueror package.


%package dev
Summary: dev components for the konqueror package.
Group: Development
Requires: konqueror-lib = %{version}-%{release}
Requires: konqueror-bin = %{version}-%{release}
Requires: konqueror-data = %{version}-%{release}
Provides: konqueror-devel = %{version}-%{release}
Requires: konqueror = %{version}-%{release}

%description dev
dev components for the konqueror package.


%package doc
Summary: doc components for the konqueror package.
Group: Documentation

%description doc
doc components for the konqueror package.


%package lib
Summary: lib components for the konqueror package.
Group: Libraries
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}

%description lib
lib components for the konqueror package.


%package license
Summary: license components for the konqueror package.
Group: Default

%description license
license components for the konqueror package.


%package locales
Summary: locales components for the konqueror package.
Group: Default

%description locales
locales components for the konqueror package.


%prep
%setup -q -n konqueror-20.08.0
cd %{_builddir}/konqueror-20.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1597791053
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1597791053
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/konqueror
cp %{_builddir}/konqueror-20.08.0/COPYING %{buildroot}/usr/share/package-licenses/konqueror/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/konqueror-20.08.0/COPYING.DOC %{buildroot}/usr/share/package-licenses/konqueror/e1d31e42d2a477d6def889000aa8ffc251f2354c
cp %{_builddir}/konqueror-20.08.0/COPYING.LIB %{buildroot}/usr/share/package-licenses/konqueror/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/konqueror-20.08.0/libkonq/COPYING %{buildroot}/usr/share/package-licenses/konqueror/7c203dee3a03037da436df03c4b25b659c073976
cp %{_builddir}/konqueror-20.08.0/libkonq/COPYING.LIB %{buildroot}/usr/share/package-licenses/konqueror/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/konqueror-20.08.0/plugins/COPYING %{buildroot}/usr/share/package-licenses/konqueror/7c203dee3a03037da436df03c4b25b659c073976
cp %{_builddir}/konqueror-20.08.0/plugins/COPYING.DOC %{buildroot}/usr/share/package-licenses/konqueror/bd75d59f9d7d9731bfabdc48ecd19e704d218e38
cp %{_builddir}/konqueror-20.08.0/plugins/COPYING.LIB %{buildroot}/usr/share/package-licenses/konqueror/9a1929f4700d2407c70b507b3b2aaf6226a9543c
cp %{_builddir}/konqueror-20.08.0/webenginepart/COPYING.LIB %{buildroot}/usr/share/package-licenses/konqueror/6c3f140c3d22440a55cccd8dd7dd348115e67968
pushd clr-build
%make_install
popd
%find_lang akregator_konqplugin
%find_lang autorefresh
%find_lang babelfish
%find_lang dirfilterplugin
%find_lang fsview
%find_lang imgalleryplugin
%find_lang kcmbookmarks
%find_lang kcmkonq
%find_lang kcmkonqhtml
%find_lang kcmperformance
%find_lang kfmclient
%find_lang khtmlsettingsplugin
%find_lang khtmltts
%find_lang konqueror
%find_lang kshellcmdplugin
%find_lang libkonq
%find_lang searchbarplugin
%find_lang uachangerplugin
%find_lang webenginepart

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fsview
/usr/bin/kfmclient
/usr/bin/konqueror

%files data
%defattr(-,root,root,-)
/usr/share/akregator/pics/feed.png
/usr/share/applications/kfmclient.desktop
/usr/share/applications/kfmclient_dir.desktop
/usr/share/applications/kfmclient_html.desktop
/usr/share/applications/kfmclient_war.desktop
/usr/share/applications/konqbrowser.desktop
/usr/share/config.kcfg/konqueror.kcfg
/usr/share/dbus-1/interfaces/org.kde.Konqueror.Main.xml
/usr/share/dbus-1/interfaces/org.kde.Konqueror.MainWindow.xml
/usr/share/dolphinpart/kpartplugins/dirfilterplugin.desktop
/usr/share/dolphinpart/kpartplugins/dirfilterplugin.rc
/usr/share/dolphinpart/kpartplugins/kimgalleryplugin.desktop
/usr/share/dolphinpart/kpartplugins/kimgalleryplugin.rc
/usr/share/dolphinpart/kpartplugins/kshellcmdplugin.desktop
/usr/share/dolphinpart/kpartplugins/kshellcmdplugin.rc
/usr/share/icons/hicolor/128x128/apps/konqueror.png
/usr/share/icons/hicolor/128x128/apps/webengine.png
/usr/share/icons/hicolor/16x16/actions/babelfish.png
/usr/share/icons/hicolor/16x16/actions/imagegallery.png
/usr/share/icons/hicolor/16x16/apps/konqueror.png
/usr/share/icons/hicolor/16x16/apps/webengine.png
/usr/share/icons/hicolor/22x22/actions/babelfish.png
/usr/share/icons/hicolor/22x22/actions/imagegallery.png
/usr/share/icons/hicolor/22x22/apps/fsview.png
/usr/share/icons/hicolor/22x22/apps/konqueror.png
/usr/share/icons/hicolor/22x22/apps/webengine.png
/usr/share/icons/hicolor/32x32/apps/fsview.png
/usr/share/icons/hicolor/32x32/apps/konqueror.png
/usr/share/icons/hicolor/32x32/apps/webengine.png
/usr/share/icons/hicolor/48x48/apps/konqueror.png
/usr/share/icons/hicolor/48x48/apps/webengine.png
/usr/share/icons/hicolor/64x64/apps/konqueror.png
/usr/share/icons/hicolor/64x64/apps/webengine.png
/usr/share/kcmcss/template.css
/usr/share/kcontrol/pics/onlyone.png
/usr/share/kcontrol/pics/overlapping.png
/usr/share/kf5/kbookmark/directory_bookmarkbar.desktop
/usr/share/khtml/kpartplugins/akregator_konqfeedicon.desktop
/usr/share/khtml/kpartplugins/akregator_konqfeedicon.rc
/usr/share/khtml/kpartplugins/autorefresh.desktop
/usr/share/khtml/kpartplugins/autorefresh.rc
/usr/share/khtml/kpartplugins/khtmlsettingsplugin.desktop
/usr/share/khtml/kpartplugins/khtmlsettingsplugin.rc
/usr/share/khtml/kpartplugins/khtmltts.desktop
/usr/share/khtml/kpartplugins/khtmltts.rc
/usr/share/khtml/kpartplugins/plugin_babelfish.rc
/usr/share/khtml/kpartplugins/plugin_translator.desktop
/usr/share/khtml/kpartplugins/uachangerplugin.desktop
/usr/share/khtml/kpartplugins/uachangerplugin.rc
/usr/share/konqsidebartng/entries/bookmarks.desktop
/usr/share/konqsidebartng/entries/fonts.desktop
/usr/share/konqsidebartng/entries/history.desktop
/usr/share/konqsidebartng/entries/home.desktop
/usr/share/konqsidebartng/entries/places.desktop
/usr/share/konqsidebartng/entries/remote.desktop
/usr/share/konqsidebartng/entries/root.desktop
/usr/share/konqsidebartng/entries/services.desktop
/usr/share/konqsidebartng/entries/settings.desktop
/usr/share/konqsidebartng/plugins/konqsidebar_bookmarks.desktop
/usr/share/konqsidebartng/plugins/konqsidebar_history.desktop
/usr/share/konqsidebartng/plugins/konqsidebar_places.desktop
/usr/share/konqsidebartng/plugins/konqsidebar_tree.desktop
/usr/share/konqueror/about/intro.html
/usr/share/konqueror/about/konq.css
/usr/share/konqueror/about/launch.html
/usr/share/konqueror/about/plugins.html
/usr/share/konqueror/about/plugins_rtl.html
/usr/share/konqueror/about/specs.html
/usr/share/konqueror/about/tips.html
/usr/share/konqueror/about/top-left-konqueror.png
/usr/share/konqueror/icons/hicolor/16x16/actions/google.png
/usr/share/konqueror/icons/hicolor/22x22/actions/google.png
/usr/share/konqueror/icons/hicolor/32x32/actions/google.png
/usr/share/konqueror/icons/hicolor/48x48/actions/google.png
/usr/share/konqueror/icons/hicolor/64x64/actions/google.png
/usr/share/konqueror/icons/hicolor/scalable/actions/google.svgz
/usr/share/konqueror/kpartplugins/searchbar.desktop
/usr/share/konqueror/kpartplugins/searchbar.rc
/usr/share/konqueror/opensearch/google.xml
/usr/share/konqueror/pics/indicator_connect.png
/usr/share/konqueror/pics/indicator_empty.png
/usr/share/konqueror/pics/indicator_noconnect.png
/usr/share/konqueror/pics/indicator_viewactive.png
/usr/share/kservices5/akregator_konqplugin.desktop
/usr/share/kservices5/bookmarks.desktop
/usr/share/kservices5/filebehavior.desktop
/usr/share/kservices5/fsview_part.desktop
/usr/share/kservices5/kcmhistory.desktop
/usr/share/kservices5/kcmkonqyperformance.desktop
/usr/share/kservices5/kcmperformance.desktop
/usr/share/kservices5/khtml_appearance.desktop
/usr/share/kservices5/khtml_behavior.desktop
/usr/share/kservices5/khtml_filter.desktop
/usr/share/kservices5/khtml_general.desktop
/usr/share/kservices5/khtml_java_js.desktop
/usr/share/kservices5/konq_sidebartng.desktop
/usr/share/kservices5/org.kde.konqueror.desktop
/usr/share/kservices5/webenginepart.desktop
/usr/share/kwebkitpart/kpartplugins/akregator_konqfeedicon.desktop
/usr/share/kwebkitpart/kpartplugins/akregator_konqfeedicon.rc
/usr/share/kwebkitpart/kpartplugins/autorefresh.desktop
/usr/share/kwebkitpart/kpartplugins/autorefresh.rc
/usr/share/kwebkitpart/kpartplugins/khtmlsettingsplugin.desktop
/usr/share/kwebkitpart/kpartplugins/khtmlsettingsplugin.rc
/usr/share/kwebkitpart/kpartplugins/khtmltts.desktop
/usr/share/kwebkitpart/kpartplugins/khtmltts.rc
/usr/share/kwebkitpart/kpartplugins/plugin_babelfish.rc
/usr/share/kwebkitpart/kpartplugins/plugin_translator.desktop
/usr/share/kwebkitpart/kpartplugins/uachangerplugin.desktop
/usr/share/kwebkitpart/kpartplugins/uachangerplugin.rc
/usr/share/kxmlgui5/fsview/fsview_part.rc
/usr/share/kxmlgui5/webenginepart/webenginepart.rc
/usr/share/metainfo/org.kde.konqueror.appdata.xml
/usr/share/qlogging-categories5/akregatorplugin.categories
/usr/share/qlogging-categories5/fsview.categories
/usr/share/qlogging-categories5/konqueror.categories
/usr/share/webenginepart/error.html
/usr/share/webenginepart/kpartplugins/akregator_konqfeedicon.desktop
/usr/share/webenginepart/kpartplugins/akregator_konqfeedicon.rc
/usr/share/webenginepart/kpartplugins/autorefresh.desktop
/usr/share/webenginepart/kpartplugins/autorefresh.rc
/usr/share/webenginepart/kpartplugins/khtmlsettingsplugin.desktop
/usr/share/webenginepart/kpartplugins/khtmlsettingsplugin.rc
/usr/share/webenginepart/kpartplugins/khtmltts.desktop
/usr/share/webenginepart/kpartplugins/khtmltts.rc
/usr/share/webenginepart/kpartplugins/plugin_babelfish.rc
/usr/share/webenginepart/kpartplugins/plugin_translator.desktop
/usr/share/webenginepart/kpartplugins/uachangerplugin.desktop
/usr/share/webenginepart/kpartplugins/uachangerplugin.rc
/usr/share/xdg/autostart/konqy_preload.desktop
/usr/share/xdg/konqsidebartngrc
/usr/share/xdg/translaterc

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/konq_events.h
/usr/include/KF5/konq_historyentry.h
/usr/include/KF5/konq_historyprovider.h
/usr/include/KF5/konq_popupmenu.h
/usr/include/KF5/konq_version.h
/usr/include/KF5/libkonq_export.h
/usr/include/konqsidebarplugin.h
/usr/lib64/cmake/KF5Konq/KF5KonqConfig.cmake
/usr/lib64/cmake/KF5Konq/KF5KonqConfigVersion.cmake
/usr/lib64/cmake/KF5Konq/KF5KonqTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5Konq/KF5KonqTargets.cmake
/usr/lib64/libKF5Konq.so
/usr/lib64/libkonqsidebarplugin.so
/usr/lib64/libkwebenginepart.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/history/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/ca/konqueror/index.cache.bz2
/usr/share/doc/HTML/ca/konqueror/index.docbook
/usr/share/doc/HTML/ca/konqueror/konqorg.png
/usr/share/doc/HTML/ca/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/da/konqueror/basics.docbook
/usr/share/doc/HTML/da/konqueror/bookmarks.docbook
/usr/share/doc/HTML/da/konqueror/browser.docbook
/usr/share/doc/HTML/da/konqueror/cmndline.png
/usr/share/doc/HTML/da/konqueror/commands.docbook
/usr/share/doc/HTML/da/konqueror/config.docbook
/usr/share/doc/HTML/da/konqueror/credits.docbook
/usr/share/doc/HTML/da/konqueror/dirtree.png
/usr/share/doc/HTML/da/konqueror/dragdrop.png
/usr/share/doc/HTML/da/konqueror/faq.docbook
/usr/share/doc/HTML/da/konqueror/filemanager.docbook
/usr/share/doc/HTML/da/konqueror/index.cache.bz2
/usr/share/doc/HTML/da/konqueror/index.docbook
/usr/share/doc/HTML/da/konqueror/introduction.docbook
/usr/share/doc/HTML/da/konqueror/konqorg.png
/usr/share/doc/HTML/da/konqueror/parts.png
/usr/share/doc/HTML/da/konqueror/path-complete.docbook
/usr/share/doc/HTML/da/konqueror/plugins.docbook
/usr/share/doc/HTML/da/konqueror/save-settings.docbook
/usr/share/doc/HTML/da/konqueror/shortcut1.png
/usr/share/doc/HTML/da/konqueror/shortcut2.png
/usr/share/doc/HTML/da/konqueror/sidebar.docbook
/usr/share/doc/HTML/de/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/de/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/de/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/history/index.docbook
/usr/share/doc/HTML/de/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/de/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/de/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/de/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/de/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/de/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/de/konqueror/cmndline.png
/usr/share/doc/HTML/de/konqueror/dirtree.png
/usr/share/doc/HTML/de/konqueror/dragdrop.png
/usr/share/doc/HTML/de/konqueror/folders.png
/usr/share/doc/HTML/de/konqueror/index.cache.bz2
/usr/share/doc/HTML/de/konqueror/index.docbook
/usr/share/doc/HTML/de/konqueror/konqorg.png
/usr/share/doc/HTML/de/konqueror/look.png
/usr/share/doc/HTML/de/konqueror/parts.png
/usr/share/doc/HTML/de/konqueror/shortcut1.png
/usr/share/doc/HTML/de/konqueror/shortcut2.png
/usr/share/doc/HTML/de/konqueror/thumbnails.png
/usr/share/doc/HTML/el/konqueror/basics.docbook
/usr/share/doc/HTML/el/konqueror/bookmarks.docbook
/usr/share/doc/HTML/el/konqueror/browser.docbook
/usr/share/doc/HTML/el/konqueror/cmndline.png
/usr/share/doc/HTML/el/konqueror/commands.docbook
/usr/share/doc/HTML/el/konqueror/config.docbook
/usr/share/doc/HTML/el/konqueror/credits.docbook
/usr/share/doc/HTML/el/konqueror/dirtree.png
/usr/share/doc/HTML/el/konqueror/dragdrop.png
/usr/share/doc/HTML/el/konqueror/faq.docbook
/usr/share/doc/HTML/el/konqueror/filemanager.docbook
/usr/share/doc/HTML/el/konqueror/folders.png
/usr/share/doc/HTML/el/konqueror/index.cache.bz2
/usr/share/doc/HTML/el/konqueror/index.docbook
/usr/share/doc/HTML/el/konqueror/introduction.docbook
/usr/share/doc/HTML/el/konqueror/konqorg.png
/usr/share/doc/HTML/el/konqueror/look.png
/usr/share/doc/HTML/el/konqueror/parts.png
/usr/share/doc/HTML/el/konqueror/path-complete.docbook
/usr/share/doc/HTML/el/konqueror/plugins.docbook
/usr/share/doc/HTML/el/konqueror/save-settings.docbook
/usr/share/doc/HTML/el/konqueror/shortcut1.png
/usr/share/doc/HTML/el/konqueror/shortcut2.png
/usr/share/doc/HTML/el/konqueror/sidebar.docbook
/usr/share/doc/HTML/el/konqueror/thumbnails.png
/usr/share/doc/HTML/el/konqueror/view-extensions.docbook
/usr/share/doc/HTML/el/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/en/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/en/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/en/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/en/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/en/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/en/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/en/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/en/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/en/konqueror/cmndline.png
/usr/share/doc/HTML/en/konqueror/dirtree.png
/usr/share/doc/HTML/en/konqueror/dragdrop.png
/usr/share/doc/HTML/en/konqueror/folders.png
/usr/share/doc/HTML/en/konqueror/format-font-size-less.png
/usr/share/doc/HTML/en/konqueror/format-font-size-more.png
/usr/share/doc/HTML/en/konqueror/go-jump.png
/usr/share/doc/HTML/en/konqueror/grouping-view.png
/usr/share/doc/HTML/en/konqueror/index.cache.bz2
/usr/share/doc/HTML/en/konqueror/index.docbook
/usr/share/doc/HTML/en/konqueror/konqorg.png
/usr/share/doc/HTML/en/konqueror/look.png
/usr/share/doc/HTML/en/konqueror/parts.png
/usr/share/doc/HTML/en/konqueror/reset.png
/usr/share/doc/HTML/en/konqueror/thumbnails.png
/usr/share/doc/HTML/en/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/en_GB/konqueror/basics.docbook
/usr/share/doc/HTML/en_GB/konqueror/bookmarks.docbook
/usr/share/doc/HTML/en_GB/konqueror/browser.docbook
/usr/share/doc/HTML/en_GB/konqueror/commands.docbook
/usr/share/doc/HTML/en_GB/konqueror/config.docbook
/usr/share/doc/HTML/en_GB/konqueror/credits.docbook
/usr/share/doc/HTML/en_GB/konqueror/faq.docbook
/usr/share/doc/HTML/en_GB/konqueror/filemanager.docbook
/usr/share/doc/HTML/en_GB/konqueror/index.cache.bz2
/usr/share/doc/HTML/en_GB/konqueror/index.docbook
/usr/share/doc/HTML/en_GB/konqueror/introduction.docbook
/usr/share/doc/HTML/en_GB/konqueror/path-complete.docbook
/usr/share/doc/HTML/en_GB/konqueror/plugins.docbook
/usr/share/doc/HTML/en_GB/konqueror/save-settings.docbook
/usr/share/doc/HTML/en_GB/konqueror/sidebar.docbook
/usr/share/doc/HTML/es/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/es/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/es/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/history/index.docbook
/usr/share/doc/HTML/es/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/es/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/es/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/es/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/es/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/es/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/es/konqueror/basics.docbook
/usr/share/doc/HTML/es/konqueror/bookmarks.docbook
/usr/share/doc/HTML/es/konqueror/browser.docbook
/usr/share/doc/HTML/es/konqueror/commands.docbook
/usr/share/doc/HTML/es/konqueror/config.docbook
/usr/share/doc/HTML/es/konqueror/credits.docbook
/usr/share/doc/HTML/es/konqueror/faq.docbook
/usr/share/doc/HTML/es/konqueror/filemanager.docbook
/usr/share/doc/HTML/es/konqueror/index.cache.bz2
/usr/share/doc/HTML/es/konqueror/index.docbook
/usr/share/doc/HTML/es/konqueror/introduction.docbook
/usr/share/doc/HTML/es/konqueror/path-complete.docbook
/usr/share/doc/HTML/es/konqueror/plugins.docbook
/usr/share/doc/HTML/es/konqueror/save-settings.docbook
/usr/share/doc/HTML/es/konqueror/sidebar.docbook
/usr/share/doc/HTML/es/konqueror/view-extensions.docbook
/usr/share/doc/HTML/et/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/et/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/et/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/history/index.docbook
/usr/share/doc/HTML/et/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/et/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/et/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/et/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/et/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/et/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/history/index.docbook
/usr/share/doc/HTML/fr/konqueror/basics.docbook
/usr/share/doc/HTML/fr/konqueror/bookmarks.docbook
/usr/share/doc/HTML/fr/konqueror/browser.docbook
/usr/share/doc/HTML/fr/konqueror/cmndline.png
/usr/share/doc/HTML/fr/konqueror/commands.docbook
/usr/share/doc/HTML/fr/konqueror/config.docbook
/usr/share/doc/HTML/fr/konqueror/credits.docbook
/usr/share/doc/HTML/fr/konqueror/dirtree.png
/usr/share/doc/HTML/fr/konqueror/dragdrop.png
/usr/share/doc/HTML/fr/konqueror/faq.docbook
/usr/share/doc/HTML/fr/konqueror/filemanager.docbook
/usr/share/doc/HTML/fr/konqueror/index.cache.bz2
/usr/share/doc/HTML/fr/konqueror/index.docbook
/usr/share/doc/HTML/fr/konqueror/introduction.docbook
/usr/share/doc/HTML/fr/konqueror/konqorg.png
/usr/share/doc/HTML/fr/konqueror/parts.png
/usr/share/doc/HTML/fr/konqueror/path-complete.docbook
/usr/share/doc/HTML/fr/konqueror/plugins.docbook
/usr/share/doc/HTML/fr/konqueror/save-settings.docbook
/usr/share/doc/HTML/fr/konqueror/shortcut1.png
/usr/share/doc/HTML/fr/konqueror/shortcut2.png
/usr/share/doc/HTML/fr/konqueror/sidebar.docbook
/usr/share/doc/HTML/fr/konqueror/view-extensions.docbook
/usr/share/doc/HTML/it/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/it/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/it/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/history/index.docbook
/usr/share/doc/HTML/it/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/it/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/it/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/it/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/it/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/it/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/it/konqueror/index.cache.bz2
/usr/share/doc/HTML/it/konqueror/index.docbook
/usr/share/doc/HTML/ko/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/ko/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/nb/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/nb/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol5/history/index.docbook
/usr/share/doc/HTML/nb/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/history/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/nl/konqueror/basics.docbook
/usr/share/doc/HTML/nl/konqueror/bookmarks.docbook
/usr/share/doc/HTML/nl/konqueror/browser.docbook
/usr/share/doc/HTML/nl/konqueror/cmndline.png
/usr/share/doc/HTML/nl/konqueror/commands.docbook
/usr/share/doc/HTML/nl/konqueror/config.docbook
/usr/share/doc/HTML/nl/konqueror/credits.docbook
/usr/share/doc/HTML/nl/konqueror/dirtree.png
/usr/share/doc/HTML/nl/konqueror/dragdrop.png
/usr/share/doc/HTML/nl/konqueror/faq.docbook
/usr/share/doc/HTML/nl/konqueror/filemanager.docbook
/usr/share/doc/HTML/nl/konqueror/index.cache.bz2
/usr/share/doc/HTML/nl/konqueror/index.docbook
/usr/share/doc/HTML/nl/konqueror/introduction.docbook
/usr/share/doc/HTML/nl/konqueror/konqorg.png
/usr/share/doc/HTML/nl/konqueror/parts.png
/usr/share/doc/HTML/nl/konqueror/path-complete.docbook
/usr/share/doc/HTML/nl/konqueror/plugins.docbook
/usr/share/doc/HTML/nl/konqueror/save-settings.docbook
/usr/share/doc/HTML/nl/konqueror/shortcut1.png
/usr/share/doc/HTML/nl/konqueror/shortcut2.png
/usr/share/doc/HTML/nl/konqueror/sidebar.docbook
/usr/share/doc/HTML/nl/konqueror/view-extensions.docbook
/usr/share/doc/HTML/pl/konqueror/basics.docbook
/usr/share/doc/HTML/pl/konqueror/bookmarks.docbook
/usr/share/doc/HTML/pl/konqueror/browser.docbook
/usr/share/doc/HTML/pl/konqueror/cmndline.png
/usr/share/doc/HTML/pl/konqueror/commands.docbook
/usr/share/doc/HTML/pl/konqueror/config.docbook
/usr/share/doc/HTML/pl/konqueror/credits.docbook
/usr/share/doc/HTML/pl/konqueror/dirtree.png
/usr/share/doc/HTML/pl/konqueror/dragdrop.png
/usr/share/doc/HTML/pl/konqueror/faq.docbook
/usr/share/doc/HTML/pl/konqueror/filemanager.docbook
/usr/share/doc/HTML/pl/konqueror/index.cache.bz2
/usr/share/doc/HTML/pl/konqueror/index.docbook
/usr/share/doc/HTML/pl/konqueror/introduction.docbook
/usr/share/doc/HTML/pl/konqueror/konqorg.png
/usr/share/doc/HTML/pl/konqueror/parts.png
/usr/share/doc/HTML/pl/konqueror/path-complete.docbook
/usr/share/doc/HTML/pl/konqueror/plugins.docbook
/usr/share/doc/HTML/pl/konqueror/save-settings.docbook
/usr/share/doc/HTML/pl/konqueror/shortcut1.png
/usr/share/doc/HTML/pl/konqueror/shortcut2.png
/usr/share/doc/HTML/pl/konqueror/sidebar.docbook
/usr/share/doc/HTML/pt/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/history/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/pt/konqueror/basics.docbook
/usr/share/doc/HTML/pt/konqueror/bookmarks.docbook
/usr/share/doc/HTML/pt/konqueror/browser.docbook
/usr/share/doc/HTML/pt/konqueror/commands.docbook
/usr/share/doc/HTML/pt/konqueror/config.docbook
/usr/share/doc/HTML/pt/konqueror/credits.docbook
/usr/share/doc/HTML/pt/konqueror/faq.docbook
/usr/share/doc/HTML/pt/konqueror/filemanager.docbook
/usr/share/doc/HTML/pt/konqueror/index.cache.bz2
/usr/share/doc/HTML/pt/konqueror/index.docbook
/usr/share/doc/HTML/pt/konqueror/introduction.docbook
/usr/share/doc/HTML/pt/konqueror/path-complete.docbook
/usr/share/doc/HTML/pt/konqueror/plugins.docbook
/usr/share/doc/HTML/pt/konqueror/save-settings.docbook
/usr/share/doc/HTML/pt/konqueror/sidebar.docbook
/usr/share/doc/HTML/pt/konqueror/view-extensions.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/history/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/pt_BR/konqueror/cmndline.png
/usr/share/doc/HTML/pt_BR/konqueror/dirtree.png
/usr/share/doc/HTML/pt_BR/konqueror/dragdrop.png
/usr/share/doc/HTML/pt_BR/konqueror/folders.png
/usr/share/doc/HTML/pt_BR/konqueror/index.cache.bz2
/usr/share/doc/HTML/pt_BR/konqueror/index.docbook
/usr/share/doc/HTML/pt_BR/konqueror/konqorg.png
/usr/share/doc/HTML/pt_BR/konqueror/look.png
/usr/share/doc/HTML/pt_BR/konqueror/parts.png
/usr/share/doc/HTML/pt_BR/konqueror/shortcut1.png
/usr/share/doc/HTML/pt_BR/konqueror/shortcut2.png
/usr/share/doc/HTML/pt_BR/konqueror/thumbnails.png
/usr/share/doc/HTML/pt_BR/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/ru/konqueror/basics.docbook
/usr/share/doc/HTML/ru/konqueror/bookmarks.docbook
/usr/share/doc/HTML/ru/konqueror/browser.docbook
/usr/share/doc/HTML/ru/konqueror/cmndline.png
/usr/share/doc/HTML/ru/konqueror/commands.docbook
/usr/share/doc/HTML/ru/konqueror/config.docbook
/usr/share/doc/HTML/ru/konqueror/credits.docbook
/usr/share/doc/HTML/ru/konqueror/dirtree.png
/usr/share/doc/HTML/ru/konqueror/dragdrop.png
/usr/share/doc/HTML/ru/konqueror/faq.docbook
/usr/share/doc/HTML/ru/konqueror/filemanager.docbook
/usr/share/doc/HTML/ru/konqueror/index.cache.bz2
/usr/share/doc/HTML/ru/konqueror/index.docbook
/usr/share/doc/HTML/ru/konqueror/introduction.docbook
/usr/share/doc/HTML/ru/konqueror/konqorg.png
/usr/share/doc/HTML/ru/konqueror/parts.png
/usr/share/doc/HTML/ru/konqueror/path-complete.docbook
/usr/share/doc/HTML/ru/konqueror/plugins.docbook
/usr/share/doc/HTML/ru/konqueror/save-settings.docbook
/usr/share/doc/HTML/ru/konqueror/shortcut1.png
/usr/share/doc/HTML/ru/konqueror/shortcut2.png
/usr/share/doc/HTML/ru/konqueror/sidebar.docbook
/usr/share/doc/HTML/sr/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/sr/konqueror/basics.docbook
/usr/share/doc/HTML/sr/konqueror/bookmarks.docbook
/usr/share/doc/HTML/sr/konqueror/browser.docbook
/usr/share/doc/HTML/sr/konqueror/commands.docbook
/usr/share/doc/HTML/sr/konqueror/config.docbook
/usr/share/doc/HTML/sr/konqueror/credits.docbook
/usr/share/doc/HTML/sr/konqueror/faq.docbook
/usr/share/doc/HTML/sr/konqueror/filemanager.docbook
/usr/share/doc/HTML/sr/konqueror/index.cache.bz2
/usr/share/doc/HTML/sr/konqueror/index.docbook
/usr/share/doc/HTML/sr/konqueror/introduction.docbook
/usr/share/doc/HTML/sr/konqueror/path-complete.docbook
/usr/share/doc/HTML/sr/konqueror/plugins.docbook
/usr/share/doc/HTML/sr/konqueror/save-settings.docbook
/usr/share/doc/HTML/sr/konqueror/sidebar.docbook
/usr/share/doc/HTML/sr/konqueror/view-extensions.docbook
/usr/share/doc/HTML/sv/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/history/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/sv/konqueror/cmndline.png
/usr/share/doc/HTML/sv/konqueror/dirtree.png
/usr/share/doc/HTML/sv/konqueror/dragdrop.png
/usr/share/doc/HTML/sv/konqueror/index.cache.bz2
/usr/share/doc/HTML/sv/konqueror/index.docbook
/usr/share/doc/HTML/sv/konqueror/konqorg.png
/usr/share/doc/HTML/sv/konqueror/parts.png
/usr/share/doc/HTML/sv/konqueror/shortcut1.png
/usr/share/doc/HTML/sv/konqueror/shortcut2.png
/usr/share/doc/HTML/uk/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/history/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/uk/konqueror/cmndline.png
/usr/share/doc/HTML/uk/konqueror/dirtree.png
/usr/share/doc/HTML/uk/konqueror/dragdrop.png
/usr/share/doc/HTML/uk/konqueror/folders.png
/usr/share/doc/HTML/uk/konqueror/index.cache.bz2
/usr/share/doc/HTML/uk/konqueror/index.docbook
/usr/share/doc/HTML/uk/konqueror/konqorg.png
/usr/share/doc/HTML/uk/konqueror/look.png
/usr/share/doc/HTML/uk/konqueror/parts.png
/usr/share/doc/HTML/uk/konqueror/thumbnails.png
/usr/share/doc/HTML/uk/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/zh_CN/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/zh_CN/kcontrol5/history/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5Konq.so.5.97.0
/usr/lib64/libKF5Konq.so.6
/usr/lib64/libkdeinit5_kfmclient.so
/usr/lib64/libkdeinit5_konqueror.so
/usr/lib64/libkonqsidebarplugin.so.20.08.0
/usr/lib64/libkonqsidebarplugin.so.5
/usr/lib64/libkonquerorprivate.so.20.08.0
/usr/lib64/libkonquerorprivate.so.5
/usr/lib64/qt5/plugins/akregatorkonqfeedicon.so
/usr/lib64/qt5/plugins/autorefresh.so
/usr/lib64/qt5/plugins/babelfishplugin.so
/usr/lib64/qt5/plugins/dirfilterplugin.so
/usr/lib64/qt5/plugins/fsviewpart.so
/usr/lib64/qt5/plugins/kcm_bookmarks.so
/usr/lib64/qt5/plugins/kcm_history.so
/usr/lib64/qt5/plugins/kcm_konq.so
/usr/lib64/qt5/plugins/kcm_konqhtml.so
/usr/lib64/qt5/plugins/kcm_performance.so
/usr/lib64/qt5/plugins/kf5/kfileitemaction/akregatorplugin.so
/usr/lib64/qt5/plugins/kf5/parts/webenginepart.so
/usr/lib64/qt5/plugins/khtmlsettingsplugin.so
/usr/lib64/qt5/plugins/khtmlttsplugin.so
/usr/lib64/qt5/plugins/kimgallery.so
/usr/lib64/qt5/plugins/konq_shellcmdplugin.so
/usr/lib64/qt5/plugins/konq_sidebar.so
/usr/lib64/qt5/plugins/konqsidebar_bookmarks.so
/usr/lib64/qt5/plugins/konqsidebar_history.so
/usr/lib64/qt5/plugins/konqsidebar_places.so
/usr/lib64/qt5/plugins/konqsidebar_tree.so
/usr/lib64/qt5/plugins/searchbarplugin.so
/usr/lib64/qt5/plugins/uachangerplugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/konqueror/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/konqueror/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/konqueror/6c3f140c3d22440a55cccd8dd7dd348115e67968
/usr/share/package-licenses/konqueror/7c203dee3a03037da436df03c4b25b659c073976
/usr/share/package-licenses/konqueror/9a1929f4700d2407c70b507b3b2aaf6226a9543c
/usr/share/package-licenses/konqueror/bd75d59f9d7d9731bfabdc48ecd19e704d218e38
/usr/share/package-licenses/konqueror/e1d31e42d2a477d6def889000aa8ffc251f2354c

%files locales -f akregator_konqplugin.lang -f autorefresh.lang -f babelfish.lang -f dirfilterplugin.lang -f fsview.lang -f imgalleryplugin.lang -f kcmbookmarks.lang -f kcmkonq.lang -f kcmkonqhtml.lang -f kcmperformance.lang -f kfmclient.lang -f khtmlsettingsplugin.lang -f khtmltts.lang -f konqueror.lang -f kshellcmdplugin.lang -f libkonq.lang -f searchbarplugin.lang -f uachangerplugin.lang -f webenginepart.lang
%defattr(-,root,root,-)

