#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : konqueror
Version  : 22.08.3
Release  : 49
URL      : https://download.kde.org/stable/release-service/22.08.3/src/konqueror-22.08.3.tar.xz
Source0  : https://download.kde.org/stable/release-service/22.08.3/src/konqueror-22.08.3.tar.xz
Source1  : https://download.kde.org/stable/release-service/22.08.3/src/konqueror-22.08.3.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GFDL-1.2 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: konqueror-bin = %{version}-%{release}
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-lib = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}
Requires: konqueror-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : kactivities-dev
BuildRequires : kdesu-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86vm-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtspeech-dev
BuildRequires : qtwebengine-dev
BuildRequires : zlib-dev

%description
Konqueror Plugins
=====================================================================
This module contains plugins that interact with Konqueror.

%package bin
Summary: bin components for the konqueror package.
Group: Binaries
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}

%description bin
bin components for the konqueror package.


%package data
Summary: data components for the konqueror package.
Group: Data

%description data
data components for the konqueror package.


%package dev
Summary: dev components for the konqueror package.
Group: Development
Requires: konqueror-lib = %{version}-%{release}
Requires: konqueror-bin = %{version}-%{release}
Requires: konqueror-data = %{version}-%{release}
Provides: konqueror-devel = %{version}-%{release}
Requires: konqueror = %{version}-%{release}

%description dev
dev components for the konqueror package.


%package doc
Summary: doc components for the konqueror package.
Group: Documentation

%description doc
doc components for the konqueror package.


%package lib
Summary: lib components for the konqueror package.
Group: Libraries
Requires: konqueror-data = %{version}-%{release}
Requires: konqueror-license = %{version}-%{release}

%description lib
lib components for the konqueror package.


%package license
Summary: license components for the konqueror package.
Group: Default

%description license
license components for the konqueror package.


%package locales
Summary: locales components for the konqueror package.
Group: Default

%description locales
locales components for the konqueror package.


%prep
%setup -q -n konqueror-22.08.3
cd %{_builddir}/konqueror-22.08.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667871369
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1667871369
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/konqueror
cp %{_builddir}/konqueror-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/konqueror/ea97eb88ae53ec41e26f8542176ab986d7bc943a || :
cp %{_builddir}/konqueror-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/konqueror/f1946dab78e58c04c8c25ec6b074f5fc5c2830fe || :
cp %{_builddir}/konqueror-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/konqueror/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/konqueror/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/konqueror/2123756e0b1fc8243547235a33c0fcabfe3b9a51 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/konqueror/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/konqueror/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/konqueror/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/konqueror/19d98e1b6f8ef12849ea4012a052d3907f336c91 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/konqueror/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/konqueror/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/konqueror/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/konqueror-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/konqueror/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/konqueror-%{version}/plugins/COPYING.DOC %{buildroot}/usr/share/package-licenses/konqueror/bd75d59f9d7d9731bfabdc48ecd19e704d218e38 || :
pushd clr-build
%make_install
popd
%find_lang akregator_konqplugin
%find_lang autorefresh
%find_lang babelfish
%find_lang dirfilterplugin
%find_lang fsview
%find_lang imgalleryplugin
%find_lang kcmbookmarks
%find_lang kcmkonq
%find_lang kcmkonqhtml
%find_lang kcmperformance
%find_lang kfmclient
%find_lang kgetplugin
%find_lang khtmlsettingsplugin
%find_lang khtmltts
%find_lang konqueror
%find_lang kshellcmdplugin
%find_lang libkonq
%find_lang searchbarplugin
%find_lang uachangerplugin
%find_lang webenginepart
%find_lang webarchiver

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fsview
/usr/bin/kcreatewebarchive
/usr/bin/kfmclient
/usr/bin/konqueror

%files data
%defattr(-,root,root,-)
/usr/share/akregator/pics/feed.png
/usr/share/applications/kfmclient.desktop
/usr/share/applications/kfmclient_dir.desktop
/usr/share/applications/kfmclient_html.desktop
/usr/share/applications/kfmclient_war.desktop
/usr/share/applications/konqbrowser.desktop
/usr/share/applications/org.kde.konqueror.desktop
/usr/share/config.kcfg/kcreatewebarchive.kcfg
/usr/share/config.kcfg/konqueror.kcfg
/usr/share/dbus-1/interfaces/org.kde.Konqueror.Main.xml
/usr/share/dbus-1/interfaces/org.kde.Konqueror.MainWindow.xml
/usr/share/icons/hicolor/128x128/apps/konqueror.png
/usr/share/icons/hicolor/128x128/apps/webengine.png
/usr/share/icons/hicolor/16x16/actions/babelfish.png
/usr/share/icons/hicolor/16x16/actions/imagegallery.png
/usr/share/icons/hicolor/16x16/actions/webarchiver.png
/usr/share/icons/hicolor/16x16/apps/konqueror.png
/usr/share/icons/hicolor/16x16/apps/webengine.png
/usr/share/icons/hicolor/22x22/actions/babelfish.png
/usr/share/icons/hicolor/22x22/actions/imagegallery.png
/usr/share/icons/hicolor/22x22/actions/webarchiver.png
/usr/share/icons/hicolor/22x22/apps/fsview.png
/usr/share/icons/hicolor/22x22/apps/konqueror.png
/usr/share/icons/hicolor/22x22/apps/webengine.png
/usr/share/icons/hicolor/32x32/apps/fsview.png
/usr/share/icons/hicolor/32x32/apps/konqueror.png
/usr/share/icons/hicolor/32x32/apps/webengine.png
/usr/share/icons/hicolor/48x48/apps/konqueror.png
/usr/share/icons/hicolor/48x48/apps/webengine.png
/usr/share/icons/hicolor/64x64/apps/konqueror.png
/usr/share/icons/hicolor/64x64/apps/webengine.png
/usr/share/kcmcss/template.css
/usr/share/kconf_update/webenginepart.upd
/usr/share/kcontrol/pics/onlyone.png
/usr/share/kcontrol/pics/overlapping.png
/usr/share/kf5/kbookmark/directory_bookmarkbar.desktop
/usr/share/konqsidebartng/entries/bookmarks.desktop
/usr/share/konqsidebartng/entries/fonts.desktop
/usr/share/konqsidebartng/entries/history.desktop
/usr/share/konqsidebartng/entries/home.desktop
/usr/share/konqsidebartng/entries/places.desktop
/usr/share/konqsidebartng/entries/remote.desktop
/usr/share/konqsidebartng/entries/root.desktop
/usr/share/konqsidebartng/entries/services.desktop
/usr/share/konqsidebartng/plugins/konqsidebar_bookmarks.desktop
/usr/share/konqsidebartng/plugins/konqsidebar_history.desktop
/usr/share/konqsidebartng/plugins/konqsidebar_places.desktop
/usr/share/konqsidebartng/plugins/konqsidebar_tree.desktop
/usr/share/konqueror/about/intro.html
/usr/share/konqueror/about/konq.css
/usr/share/konqueror/about/launch.html
/usr/share/konqueror/about/plugins.html
/usr/share/konqueror/about/plugins_rtl.html
/usr/share/konqueror/about/specs.html
/usr/share/konqueror/about/tips.html
/usr/share/konqueror/about/top-left-konqueror.png
/usr/share/konqueror/icons/hicolor/16x16/actions/google.png
/usr/share/konqueror/icons/hicolor/22x22/actions/google.png
/usr/share/konqueror/icons/hicolor/32x32/actions/google.png
/usr/share/konqueror/icons/hicolor/48x48/actions/google.png
/usr/share/konqueror/icons/hicolor/64x64/actions/google.png
/usr/share/konqueror/icons/hicolor/scalable/actions/google.svgz
/usr/share/konqueror/partsrcfiles/akregatorkonqfeedicon.rc
/usr/share/konqueror/partsrcfiles/autorefresh.rc
/usr/share/konqueror/partsrcfiles/babelfishplugin.rc
/usr/share/konqueror/partsrcfiles/dirfilterplugin.rc
/usr/share/konqueror/partsrcfiles/khtmlsettingsplugin.rc
/usr/share/konqueror/partsrcfiles/khtmlttsplugin.rc
/usr/share/konqueror/partsrcfiles/kimgallery.rc
/usr/share/konqueror/partsrcfiles/konq_shellcmdplugin.rc
/usr/share/konqueror/partsrcfiles/konqueror_kget_browser_integration.rc
/usr/share/konqueror/partsrcfiles/searchbarplugin.rc
/usr/share/konqueror/partsrcfiles/uachangerplugin.rc
/usr/share/konqueror/partsrcfiles/webarchiverplugin.rc
/usr/share/konqueror/pics/indicator_connect.png
/usr/share/konqueror/pics/indicator_empty.png
/usr/share/konqueror/pics/indicator_noconnect.png
/usr/share/konqueror/pics/indicator_viewactive.png
/usr/share/kservices5/fsview_part.desktop
/usr/share/kservices5/konq_sidebartng.desktop
/usr/share/kservices5/org.kde.konqueror.desktop
/usr/share/kservices5/webarchivethumbnail.desktop
/usr/share/kservices5/webenginepart.desktop
/usr/share/kxmlgui5/fsview/fsview_part.rc
/usr/share/kxmlgui5/webenginepart/webenginepart.rc
/usr/share/locale/hu/LC_MESSAGES
/usr/share/metainfo/org.kde.konqueror.appdata.xml
/usr/share/qlogging-categories5/akregatorplugin.categories
/usr/share/qlogging-categories5/fsview.categories
/usr/share/qlogging-categories5/konqueror.categories
/usr/share/webenginepart/error.html
/usr/share/xdg/autostart/konqy_preload.desktop
/usr/share/xdg/konqsidebartngrc
/usr/share/xdg/translaterc

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/konq_events.h
/usr/include/KF5/konq_historyentry.h
/usr/include/KF5/konq_historyprovider.h
/usr/include/KF5/konq_kpart_plugin.h
/usr/include/KF5/konq_popupmenu.h
/usr/include/KF5/konq_version.h
/usr/include/KF5/libkonq_export.h
/usr/include/konqsidebarplugin.h
/usr/lib64/cmake/KF5Konq/KF5KonqConfig.cmake
/usr/lib64/cmake/KF5Konq/KF5KonqConfigVersion.cmake
/usr/lib64/cmake/KF5Konq/KF5KonqTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5Konq/KF5KonqTargets.cmake
/usr/lib64/libKF5Konq.so
/usr/lib64/libkonqsidebarplugin.so
/usr/lib64/libkwebenginepart.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/history/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/ca/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/ca/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/ca/konqueror/index.cache.bz2
/usr/share/doc/HTML/ca/konqueror/index.docbook
/usr/share/doc/HTML/ca/konqueror/konqorg.png
/usr/share/doc/HTML/ca/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/da/konqueror/basics.docbook
/usr/share/doc/HTML/da/konqueror/bookmarks.docbook
/usr/share/doc/HTML/da/konqueror/browser.docbook
/usr/share/doc/HTML/da/konqueror/cmndline.png
/usr/share/doc/HTML/da/konqueror/commands.docbook
/usr/share/doc/HTML/da/konqueror/config.docbook
/usr/share/doc/HTML/da/konqueror/credits.docbook
/usr/share/doc/HTML/da/konqueror/dirtree.png
/usr/share/doc/HTML/da/konqueror/dragdrop.png
/usr/share/doc/HTML/da/konqueror/faq.docbook
/usr/share/doc/HTML/da/konqueror/filemanager.docbook
/usr/share/doc/HTML/da/konqueror/index.cache.bz2
/usr/share/doc/HTML/da/konqueror/index.docbook
/usr/share/doc/HTML/da/konqueror/introduction.docbook
/usr/share/doc/HTML/da/konqueror/konqorg.png
/usr/share/doc/HTML/da/konqueror/parts.png
/usr/share/doc/HTML/da/konqueror/path-complete.docbook
/usr/share/doc/HTML/da/konqueror/plugins.docbook
/usr/share/doc/HTML/da/konqueror/save-settings.docbook
/usr/share/doc/HTML/da/konqueror/shortcut1.png
/usr/share/doc/HTML/da/konqueror/shortcut2.png
/usr/share/doc/HTML/da/konqueror/sidebar.docbook
/usr/share/doc/HTML/de/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/de/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/de/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/history/index.docbook
/usr/share/doc/HTML/de/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/de/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/de/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/de/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/de/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/de/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/de/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/de/konqueror/cmndline.png
/usr/share/doc/HTML/de/konqueror/dirtree.png
/usr/share/doc/HTML/de/konqueror/dragdrop.png
/usr/share/doc/HTML/de/konqueror/folders.png
/usr/share/doc/HTML/de/konqueror/index.cache.bz2
/usr/share/doc/HTML/de/konqueror/index.docbook
/usr/share/doc/HTML/de/konqueror/konqorg.png
/usr/share/doc/HTML/de/konqueror/look.png
/usr/share/doc/HTML/de/konqueror/parts.png
/usr/share/doc/HTML/de/konqueror/shortcut1.png
/usr/share/doc/HTML/de/konqueror/shortcut2.png
/usr/share/doc/HTML/de/konqueror/thumbnails.png
/usr/share/doc/HTML/el/konqueror/basics.docbook
/usr/share/doc/HTML/el/konqueror/bookmarks.docbook
/usr/share/doc/HTML/el/konqueror/browser.docbook
/usr/share/doc/HTML/el/konqueror/cmndline.png
/usr/share/doc/HTML/el/konqueror/commands.docbook
/usr/share/doc/HTML/el/konqueror/config.docbook
/usr/share/doc/HTML/el/konqueror/credits.docbook
/usr/share/doc/HTML/el/konqueror/dirtree.png
/usr/share/doc/HTML/el/konqueror/dragdrop.png
/usr/share/doc/HTML/el/konqueror/faq.docbook
/usr/share/doc/HTML/el/konqueror/filemanager.docbook
/usr/share/doc/HTML/el/konqueror/folders.png
/usr/share/doc/HTML/el/konqueror/index.cache.bz2
/usr/share/doc/HTML/el/konqueror/index.docbook
/usr/share/doc/HTML/el/konqueror/introduction.docbook
/usr/share/doc/HTML/el/konqueror/konqorg.png
/usr/share/doc/HTML/el/konqueror/look.png
/usr/share/doc/HTML/el/konqueror/parts.png
/usr/share/doc/HTML/el/konqueror/path-complete.docbook
/usr/share/doc/HTML/el/konqueror/plugins.docbook
/usr/share/doc/HTML/el/konqueror/save-settings.docbook
/usr/share/doc/HTML/el/konqueror/shortcut1.png
/usr/share/doc/HTML/el/konqueror/shortcut2.png
/usr/share/doc/HTML/el/konqueror/sidebar.docbook
/usr/share/doc/HTML/el/konqueror/thumbnails.png
/usr/share/doc/HTML/el/konqueror/view-extensions.docbook
/usr/share/doc/HTML/el/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/en/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/en/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/en/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/en/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/en/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/en/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/en/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/en/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/en/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/en/konqueror/cmndline.png
/usr/share/doc/HTML/en/konqueror/dirtree.png
/usr/share/doc/HTML/en/konqueror/dragdrop.png
/usr/share/doc/HTML/en/konqueror/folders.png
/usr/share/doc/HTML/en/konqueror/format-font-size-less.png
/usr/share/doc/HTML/en/konqueror/format-font-size-more.png
/usr/share/doc/HTML/en/konqueror/go-jump.png
/usr/share/doc/HTML/en/konqueror/grouping-view.png
/usr/share/doc/HTML/en/konqueror/index.cache.bz2
/usr/share/doc/HTML/en/konqueror/index.docbook
/usr/share/doc/HTML/en/konqueror/konqorg.png
/usr/share/doc/HTML/en/konqueror/look.png
/usr/share/doc/HTML/en/konqueror/parts.png
/usr/share/doc/HTML/en/konqueror/reset.png
/usr/share/doc/HTML/en/konqueror/thumbnails.png
/usr/share/doc/HTML/en/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/en_GB/konqueror/basics.docbook
/usr/share/doc/HTML/en_GB/konqueror/bookmarks.docbook
/usr/share/doc/HTML/en_GB/konqueror/browser.docbook
/usr/share/doc/HTML/en_GB/konqueror/commands.docbook
/usr/share/doc/HTML/en_GB/konqueror/config.docbook
/usr/share/doc/HTML/en_GB/konqueror/credits.docbook
/usr/share/doc/HTML/en_GB/konqueror/faq.docbook
/usr/share/doc/HTML/en_GB/konqueror/filemanager.docbook
/usr/share/doc/HTML/en_GB/konqueror/index.cache.bz2
/usr/share/doc/HTML/en_GB/konqueror/index.docbook
/usr/share/doc/HTML/en_GB/konqueror/introduction.docbook
/usr/share/doc/HTML/en_GB/konqueror/path-complete.docbook
/usr/share/doc/HTML/en_GB/konqueror/plugins.docbook
/usr/share/doc/HTML/en_GB/konqueror/save-settings.docbook
/usr/share/doc/HTML/en_GB/konqueror/sidebar.docbook
/usr/share/doc/HTML/es/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/es/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/es/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/history/index.docbook
/usr/share/doc/HTML/es/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/es/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/es/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/es/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/es/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/es/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/es/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/es/konqueror/basics.docbook
/usr/share/doc/HTML/es/konqueror/bookmarks.docbook
/usr/share/doc/HTML/es/konqueror/browser.docbook
/usr/share/doc/HTML/es/konqueror/commands.docbook
/usr/share/doc/HTML/es/konqueror/config.docbook
/usr/share/doc/HTML/es/konqueror/credits.docbook
/usr/share/doc/HTML/es/konqueror/faq.docbook
/usr/share/doc/HTML/es/konqueror/filemanager.docbook
/usr/share/doc/HTML/es/konqueror/index.cache.bz2
/usr/share/doc/HTML/es/konqueror/index.docbook
/usr/share/doc/HTML/es/konqueror/introduction.docbook
/usr/share/doc/HTML/es/konqueror/path-complete.docbook
/usr/share/doc/HTML/es/konqueror/plugins.docbook
/usr/share/doc/HTML/es/konqueror/save-settings.docbook
/usr/share/doc/HTML/es/konqueror/sidebar.docbook
/usr/share/doc/HTML/es/konqueror/view-extensions.docbook
/usr/share/doc/HTML/et/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/et/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/et/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/history/index.docbook
/usr/share/doc/HTML/et/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/et/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/et/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/et/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/et/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/et/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/et/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/history/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/fr/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/fr/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/fr/konqueror/basics.docbook
/usr/share/doc/HTML/fr/konqueror/bookmarks.docbook
/usr/share/doc/HTML/fr/konqueror/browser.docbook
/usr/share/doc/HTML/fr/konqueror/cmndline.png
/usr/share/doc/HTML/fr/konqueror/commands.docbook
/usr/share/doc/HTML/fr/konqueror/config.docbook
/usr/share/doc/HTML/fr/konqueror/credits.docbook
/usr/share/doc/HTML/fr/konqueror/dirtree.png
/usr/share/doc/HTML/fr/konqueror/dragdrop.png
/usr/share/doc/HTML/fr/konqueror/faq.docbook
/usr/share/doc/HTML/fr/konqueror/filemanager.docbook
/usr/share/doc/HTML/fr/konqueror/index.cache.bz2
/usr/share/doc/HTML/fr/konqueror/index.docbook
/usr/share/doc/HTML/fr/konqueror/introduction.docbook
/usr/share/doc/HTML/fr/konqueror/konqorg.png
/usr/share/doc/HTML/fr/konqueror/parts.png
/usr/share/doc/HTML/fr/konqueror/path-complete.docbook
/usr/share/doc/HTML/fr/konqueror/plugins.docbook
/usr/share/doc/HTML/fr/konqueror/save-settings.docbook
/usr/share/doc/HTML/fr/konqueror/shortcut1.png
/usr/share/doc/HTML/fr/konqueror/shortcut2.png
/usr/share/doc/HTML/fr/konqueror/sidebar.docbook
/usr/share/doc/HTML/fr/konqueror/view-extensions.docbook
/usr/share/doc/HTML/it/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/it/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/it/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/history/index.docbook
/usr/share/doc/HTML/it/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/it/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/it/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/it/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/it/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/it/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/it/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/it/konqueror/index.cache.bz2
/usr/share/doc/HTML/it/konqueror/index.docbook
/usr/share/doc/HTML/ko/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/ko/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/nb/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/nb/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol5/history/index.docbook
/usr/share/doc/HTML/nb/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/nb/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/history/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/nl/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/nl/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/nl/konqueror/basics.docbook
/usr/share/doc/HTML/nl/konqueror/bookmarks.docbook
/usr/share/doc/HTML/nl/konqueror/browser.docbook
/usr/share/doc/HTML/nl/konqueror/cmndline.png
/usr/share/doc/HTML/nl/konqueror/commands.docbook
/usr/share/doc/HTML/nl/konqueror/config.docbook
/usr/share/doc/HTML/nl/konqueror/credits.docbook
/usr/share/doc/HTML/nl/konqueror/dirtree.png
/usr/share/doc/HTML/nl/konqueror/dragdrop.png
/usr/share/doc/HTML/nl/konqueror/faq.docbook
/usr/share/doc/HTML/nl/konqueror/filemanager.docbook
/usr/share/doc/HTML/nl/konqueror/index.cache.bz2
/usr/share/doc/HTML/nl/konqueror/index.docbook
/usr/share/doc/HTML/nl/konqueror/introduction.docbook
/usr/share/doc/HTML/nl/konqueror/konqorg.png
/usr/share/doc/HTML/nl/konqueror/parts.png
/usr/share/doc/HTML/nl/konqueror/path-complete.docbook
/usr/share/doc/HTML/nl/konqueror/plugins.docbook
/usr/share/doc/HTML/nl/konqueror/save-settings.docbook
/usr/share/doc/HTML/nl/konqueror/shortcut1.png
/usr/share/doc/HTML/nl/konqueror/shortcut2.png
/usr/share/doc/HTML/nl/konqueror/sidebar.docbook
/usr/share/doc/HTML/nl/konqueror/view-extensions.docbook
/usr/share/doc/HTML/pl/konqueror/basics.docbook
/usr/share/doc/HTML/pl/konqueror/bookmarks.docbook
/usr/share/doc/HTML/pl/konqueror/browser.docbook
/usr/share/doc/HTML/pl/konqueror/cmndline.png
/usr/share/doc/HTML/pl/konqueror/commands.docbook
/usr/share/doc/HTML/pl/konqueror/config.docbook
/usr/share/doc/HTML/pl/konqueror/credits.docbook
/usr/share/doc/HTML/pl/konqueror/dirtree.png
/usr/share/doc/HTML/pl/konqueror/dragdrop.png
/usr/share/doc/HTML/pl/konqueror/faq.docbook
/usr/share/doc/HTML/pl/konqueror/filemanager.docbook
/usr/share/doc/HTML/pl/konqueror/index.cache.bz2
/usr/share/doc/HTML/pl/konqueror/index.docbook
/usr/share/doc/HTML/pl/konqueror/introduction.docbook
/usr/share/doc/HTML/pl/konqueror/konqorg.png
/usr/share/doc/HTML/pl/konqueror/parts.png
/usr/share/doc/HTML/pl/konqueror/path-complete.docbook
/usr/share/doc/HTML/pl/konqueror/plugins.docbook
/usr/share/doc/HTML/pl/konqueror/save-settings.docbook
/usr/share/doc/HTML/pl/konqueror/shortcut1.png
/usr/share/doc/HTML/pl/konqueror/shortcut2.png
/usr/share/doc/HTML/pl/konqueror/sidebar.docbook
/usr/share/doc/HTML/pt/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/history/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/pt/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/pt/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/pt/konqueror/basics.docbook
/usr/share/doc/HTML/pt/konqueror/bookmarks.docbook
/usr/share/doc/HTML/pt/konqueror/browser.docbook
/usr/share/doc/HTML/pt/konqueror/commands.docbook
/usr/share/doc/HTML/pt/konqueror/config.docbook
/usr/share/doc/HTML/pt/konqueror/credits.docbook
/usr/share/doc/HTML/pt/konqueror/faq.docbook
/usr/share/doc/HTML/pt/konqueror/filemanager.docbook
/usr/share/doc/HTML/pt/konqueror/index.cache.bz2
/usr/share/doc/HTML/pt/konqueror/index.docbook
/usr/share/doc/HTML/pt/konqueror/introduction.docbook
/usr/share/doc/HTML/pt/konqueror/path-complete.docbook
/usr/share/doc/HTML/pt/konqueror/plugins.docbook
/usr/share/doc/HTML/pt/konqueror/save-settings.docbook
/usr/share/doc/HTML/pt/konqueror/sidebar.docbook
/usr/share/doc/HTML/pt/konqueror/view-extensions.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/history/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/pt_BR/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/pt_BR/konqueror/cmndline.png
/usr/share/doc/HTML/pt_BR/konqueror/dirtree.png
/usr/share/doc/HTML/pt_BR/konqueror/dragdrop.png
/usr/share/doc/HTML/pt_BR/konqueror/folders.png
/usr/share/doc/HTML/pt_BR/konqueror/index.cache.bz2
/usr/share/doc/HTML/pt_BR/konqueror/index.docbook
/usr/share/doc/HTML/pt_BR/konqueror/konqorg.png
/usr/share/doc/HTML/pt_BR/konqueror/look.png
/usr/share/doc/HTML/pt_BR/konqueror/parts.png
/usr/share/doc/HTML/pt_BR/konqueror/shortcut1.png
/usr/share/doc/HTML/pt_BR/konqueror/shortcut2.png
/usr/share/doc/HTML/pt_BR/konqueror/thumbnails.png
/usr/share/doc/HTML/pt_BR/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/ru/konqueror/basics.docbook
/usr/share/doc/HTML/ru/konqueror/bookmarks.docbook
/usr/share/doc/HTML/ru/konqueror/browser.docbook
/usr/share/doc/HTML/ru/konqueror/cmndline.png
/usr/share/doc/HTML/ru/konqueror/commands.docbook
/usr/share/doc/HTML/ru/konqueror/config.docbook
/usr/share/doc/HTML/ru/konqueror/credits.docbook
/usr/share/doc/HTML/ru/konqueror/dirtree.png
/usr/share/doc/HTML/ru/konqueror/dragdrop.png
/usr/share/doc/HTML/ru/konqueror/faq.docbook
/usr/share/doc/HTML/ru/konqueror/filemanager.docbook
/usr/share/doc/HTML/ru/konqueror/index.cache.bz2
/usr/share/doc/HTML/ru/konqueror/index.docbook
/usr/share/doc/HTML/ru/konqueror/introduction.docbook
/usr/share/doc/HTML/ru/konqueror/konqorg.png
/usr/share/doc/HTML/ru/konqueror/parts.png
/usr/share/doc/HTML/ru/konqueror/path-complete.docbook
/usr/share/doc/HTML/ru/konqueror/plugins.docbook
/usr/share/doc/HTML/ru/konqueror/save-settings.docbook
/usr/share/doc/HTML/ru/konqueror/shortcut1.png
/usr/share/doc/HTML/ru/konqueror/shortcut2.png
/usr/share/doc/HTML/ru/konqueror/sidebar.docbook
/usr/share/doc/HTML/sr/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/sr/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/sr/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/sr/konqueror/basics.docbook
/usr/share/doc/HTML/sr/konqueror/bookmarks.docbook
/usr/share/doc/HTML/sr/konqueror/browser.docbook
/usr/share/doc/HTML/sr/konqueror/commands.docbook
/usr/share/doc/HTML/sr/konqueror/config.docbook
/usr/share/doc/HTML/sr/konqueror/credits.docbook
/usr/share/doc/HTML/sr/konqueror/faq.docbook
/usr/share/doc/HTML/sr/konqueror/filemanager.docbook
/usr/share/doc/HTML/sr/konqueror/index.cache.bz2
/usr/share/doc/HTML/sr/konqueror/index.docbook
/usr/share/doc/HTML/sr/konqueror/introduction.docbook
/usr/share/doc/HTML/sr/konqueror/path-complete.docbook
/usr/share/doc/HTML/sr/konqueror/plugins.docbook
/usr/share/doc/HTML/sr/konqueror/save-settings.docbook
/usr/share/doc/HTML/sr/konqueror/sidebar.docbook
/usr/share/doc/HTML/sr/konqueror/view-extensions.docbook
/usr/share/doc/HTML/sv/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/history/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/sv/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/sv/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/sv/konqueror/cmndline.png
/usr/share/doc/HTML/sv/konqueror/dirtree.png
/usr/share/doc/HTML/sv/konqueror/dragdrop.png
/usr/share/doc/HTML/sv/konqueror/index.cache.bz2
/usr/share/doc/HTML/sv/konqueror/index.docbook
/usr/share/doc/HTML/sv/konqueror/konqorg.png
/usr/share/doc/HTML/sv/konqueror/parts.png
/usr/share/doc/HTML/sv/konqueror/shortcut1.png
/usr/share/doc/HTML/sv/konqueror/shortcut2.png
/usr/share/doc/HTML/uk/kcontrol5/bookmarks/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/bookmarks/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/filemanager/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/filemanager/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/history/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/kcmcss/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/kcmcss/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/khtml-adblock/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/khtml-adblock/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/khtml-behavior/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/khtml-behavior/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/khtml-general/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/khtml-general/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/khtml-java-js/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/khtml-java-js/index.docbook
/usr/share/doc/HTML/uk/kcontrol5/performance/index.cache.bz2
/usr/share/doc/HTML/uk/kcontrol5/performance/index.docbook
/usr/share/doc/HTML/uk/konqueror/cmndline.png
/usr/share/doc/HTML/uk/konqueror/dirtree.png
/usr/share/doc/HTML/uk/konqueror/dragdrop.png
/usr/share/doc/HTML/uk/konqueror/folders.png
/usr/share/doc/HTML/uk/konqueror/index.cache.bz2
/usr/share/doc/HTML/uk/konqueror/index.docbook
/usr/share/doc/HTML/uk/konqueror/konqorg.png
/usr/share/doc/HTML/uk/konqueror/look.png
/usr/share/doc/HTML/uk/konqueror/parts.png
/usr/share/doc/HTML/uk/konqueror/thumbnails.png
/usr/share/doc/HTML/uk/konqueror/viewproperties-dialog.png
/usr/share/doc/HTML/zh_CN/kcontrol5/history/index.cache.bz2
/usr/share/doc/HTML/zh_CN/kcontrol5/history/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5Konq.so.5.97.0
/usr/lib64/libKF5Konq.so.6
/usr/lib64/libkdeinit5_kfmclient.so
/usr/lib64/libkdeinit5_konqueror.so
/usr/lib64/libkonqsidebarplugin.so.22.08.3
/usr/lib64/libkonqsidebarplugin.so.5
/usr/lib64/libkonquerorprivate.so.22.08.3
/usr/lib64/libkonquerorprivate.so.5
/usr/lib64/qt5/plugins/akregatorkonqfeedicon.so
/usr/lib64/qt5/plugins/autorefresh.so
/usr/lib64/qt5/plugins/babelfishplugin.so
/usr/lib64/qt5/plugins/dolphinpart/kpartplugins/dirfilterplugin.so
/usr/lib64/qt5/plugins/dolphinpart/kpartplugins/kimgallery.so
/usr/lib64/qt5/plugins/dolphinpart/kpartplugins/konq_shellcmdplugin.so
/usr/lib64/qt5/plugins/kf5/kfileitemaction/akregatorplugin.so
/usr/lib64/qt5/plugins/kf5/parts/fsviewpart.so
/usr/lib64/qt5/plugins/kf5/parts/konq_sidebar.so
/usr/lib64/qt5/plugins/kf5/parts/webenginepart.so
/usr/lib64/qt5/plugins/khtml/kpartplugins/akregatorkonqfeediconkhtml_kpartplugins.so
/usr/lib64/qt5/plugins/khtml/kpartplugins/autorefreshkhtml_kpartplugins.so
/usr/lib64/qt5/plugins/khtml/kpartplugins/babelfishpluginkhtml_kpartplugins.so
/usr/lib64/qt5/plugins/khtml/kpartplugins/khtmlsettingspluginkhtml_kpartplugins.so
/usr/lib64/qt5/plugins/khtml/kpartplugins/khtmlttspluginkhtml_kpartplugins.so
/usr/lib64/qt5/plugins/khtml/kpartplugins/konqueror_kget_browser_integrationkhtml_kpartplugins.so
/usr/lib64/qt5/plugins/khtml/kpartplugins/uachangerpluginkhtml_kpartplugins.so
/usr/lib64/qt5/plugins/khtml/kpartplugins/webarchiverpluginkhtml_kpartplugins.so
/usr/lib64/qt5/plugins/khtmlsettingsplugin.so
/usr/lib64/qt5/plugins/khtmlttsplugin.so
/usr/lib64/qt5/plugins/konqsidebar_bookmarks.so
/usr/lib64/qt5/plugins/konqsidebar_history.so
/usr/lib64/qt5/plugins/konqsidebar_places.so
/usr/lib64/qt5/plugins/konqsidebar_tree.so
/usr/lib64/qt5/plugins/konqueror/kpartplugins/searchbarplugin.so
/usr/lib64/qt5/plugins/konqueror_kcms/kcm_bookmarks.so
/usr/lib64/qt5/plugins/konqueror_kcms/kcm_history.so
/usr/lib64/qt5/plugins/konqueror_kcms/kcm_konq.so
/usr/lib64/qt5/plugins/konqueror_kcms/kcm_performance.so
/usr/lib64/qt5/plugins/konqueror_kcms/khtml_appearance.so
/usr/lib64/qt5/plugins/konqueror_kcms/khtml_behavior.so
/usr/lib64/qt5/plugins/konqueror_kcms/khtml_filter.so
/usr/lib64/qt5/plugins/konqueror_kcms/khtml_general.so
/usr/lib64/qt5/plugins/konqueror_kcms/khtml_java_js.so
/usr/lib64/qt5/plugins/konqueror_kget_browser_integration.so
/usr/lib64/qt5/plugins/kwebkitpart/kpartplugins/akregatorkonqfeediconkwebkitpart_kpartplugins.so
/usr/lib64/qt5/plugins/kwebkitpart/kpartplugins/autorefreshkwebkitpart_kpartplugins.so
/usr/lib64/qt5/plugins/kwebkitpart/kpartplugins/babelfishpluginkwebkitpart_kpartplugins.so
/usr/lib64/qt5/plugins/kwebkitpart/kpartplugins/khtmlsettingspluginkwebkitpart_kpartplugins.so
/usr/lib64/qt5/plugins/kwebkitpart/kpartplugins/khtmlttspluginkwebkitpart_kpartplugins.so
/usr/lib64/qt5/plugins/kwebkitpart/kpartplugins/konqueror_kget_browser_integrationkwebkitpart_kpartplugins.so
/usr/lib64/qt5/plugins/kwebkitpart/kpartplugins/uachangerpluginkwebkitpart_kpartplugins.so
/usr/lib64/qt5/plugins/kwebkitpart/kpartplugins/webarchiverpluginkwebkitpart_kpartplugins.so
/usr/lib64/qt5/plugins/uachangerplugin.so
/usr/lib64/qt5/plugins/webarchiverplugin.so
/usr/lib64/qt5/plugins/webarchivethumbnail.so
/usr/lib64/qt5/plugins/webenginepart/kpartplugins/akregatorkonqfeediconwebenginepart_kpartplugins.so
/usr/lib64/qt5/plugins/webenginepart/kpartplugins/autorefreshwebenginepart_kpartplugins.so
/usr/lib64/qt5/plugins/webenginepart/kpartplugins/babelfishpluginwebenginepart_kpartplugins.so
/usr/lib64/qt5/plugins/webenginepart/kpartplugins/khtmlsettingspluginwebenginepart_kpartplugins.so
/usr/lib64/qt5/plugins/webenginepart/kpartplugins/khtmlttspluginwebenginepart_kpartplugins.so
/usr/lib64/qt5/plugins/webenginepart/kpartplugins/konqueror_kget_browser_integrationwebenginepart_kpartplugins.so
/usr/lib64/qt5/plugins/webenginepart/kpartplugins/uachangerpluginwebenginepart_kpartplugins.so
/usr/lib64/qt5/plugins/webenginepart/kpartplugins/webarchiverpluginwebenginepart_kpartplugins.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/konqueror/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/konqueror/2123756e0b1fc8243547235a33c0fcabfe3b9a51
/usr/share/package-licenses/konqueror/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/konqueror/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/konqueror/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/konqueror/a4c60b3fefda228cd7439d3565df043192fef137
/usr/share/package-licenses/konqueror/bd75d59f9d7d9731bfabdc48ecd19e704d218e38
/usr/share/package-licenses/konqueror/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/konqueror/ea97eb88ae53ec41e26f8542176ab986d7bc943a
/usr/share/package-licenses/konqueror/f1946dab78e58c04c8c25ec6b074f5fc5c2830fe

%files locales -f akregator_konqplugin.lang -f autorefresh.lang -f babelfish.lang -f dirfilterplugin.lang -f fsview.lang -f imgalleryplugin.lang -f kcmbookmarks.lang -f kcmkonq.lang -f kcmkonqhtml.lang -f kcmperformance.lang -f kfmclient.lang -f kgetplugin.lang -f khtmlsettingsplugin.lang -f khtmltts.lang -f konqueror.lang -f kshellcmdplugin.lang -f libkonq.lang -f searchbarplugin.lang -f uachangerplugin.lang -f webenginepart.lang -f webarchiver.lang
%defattr(-,root,root,-)

